### ISSUE TITLE
Persian words showing dispatched in multiple rendering

### ISSUE THREAD

**Issue by erfansahaf** [mpdf/mpdf#486] opened 2017-09-16 13:16 UTC
I'm trying to render multiple PDF documents using following codes:
```php
require_once __DIR__ . '/vendor/autoload.php';
$template = file_get_contents('template.html');
$words = ['تست محتوا', 'یک رکورد'];
foreach($words as $word){
	$mpdf = new mPDF();
	$final = str_replace('VAR', $word, $template);
	$mpdf->WriteHTML($final);
	$mpdf->Output(time()."-".rand(0,555555).".pdf", 'F');
	unset($mpdf, $final);
}
```

Template:
```html
<html lang="fa">
<body>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style type="text/css">
        body {
            font-family: yekan;
            direction: rtl;
        }

        th {
            background: #2a2a2a;
            color: white;
            font-size: 22px;
            padding: 5px
        }

        td {
            font-size: 18px;
            padding: 10px 20px;
            text-align: center;
        }

        table {
            margin-left: auto;
            margin-right: auto;
        }

        h1 {
            margin: 20px 0 10px;
        }

        @page {
            header: page-header;
            footer: page-footer;
        }

        .text-center {
            text-align: center
        }
    </style>
</head>
<body>
<htmlpageheader name="page-header">
    <div><h1 class="text-center">سامانه آنلاین اعلام برنامه هفتگی دانشکده شمسی پور</h1></div>
    <hr>
</htmlpageheader>
<div>
	<h2 class="text-center">برنامه دروس روز </h2>
	<Br>
	<div>
		<table border="1">
			<thead>
			<tr>
				<th>ساعت</th>
				<th>نام درس</th>
				<th>نام استاد</th>
				<th>کلاس</th>
			</tr>
			</thead>
			<tbody>
				<tr>
					<td>VAR</td>
					<td>VAR</td>
					<td>VAR</td>
					<td>VAR</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
</body>
</html>
```

But there is a problem. As you know, Persian (Farsi) language is similar to Arabic (in writing) and each word contains a couple of letters that should be patched to each other to shape the word. In the first rendered document everything is fine, but after that, every rendred document contains dispatched letters and it causes dispatched words.

Here is my first rendered document which is OK:
![image](https://user-images.githubusercontent.com/12012168/30402674-d06f46f4-98f3-11e7-9dc6-6136305c654d.png)

And my second document which is NOT OK:
![image](https://user-images.githubusercontent.com/12012168/30402689-dfd5364e-98f3-11e7-92d9-9e5bba82578f.png)

**Comment by finwe** [comment] 2017-09-25 07:57
This is a duplicate of #85. It is fixed in 60d6dee in current development branch.

**Closed by finwe** 2017-09-25 07:57 UTC
Labels: bug/fix
