### ISSUE TITLE
Footer pagination only appears in last page when using a long WriteHTML content

### ISSUE THREAD

**Issue by andrw00** [mpdf/mpdf#1237] opened 2020-06-02 12:51 UTC
Simple example:
```
$mpdf->AliasNbPages('{PAGETOTAL}');
$mpdf->WriteHTML($long_html); // $long_html is, for example, a series of paragraphs resulting in a 3 page long pdf.
$mpdf->setFooter('{PAGENO}/{PAGETOTAL}'); // <- **this only prints a footer in the last page, displaying "3/3", but the other pages do not have footer**
```

**Comment by finwe** [comment] 2020-06-02 12:57
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.

**Closed by finwe** 2020-06-02 12:57 UTC

**Comment by ssieb** [comment] 2020-06-02 17:51
Pretty sure you have to set the footer before writing the html because things apply in the order they are added.
