### ISSUE TITLE
Undefined index: current (BlockTag.php:316)

### ISSUE THREAD

**Issue by bornemisza** [mpdf/mpdf#1122] opened 2019-11-13 11:56 UTC
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> For contributing here, please see the guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
>
> *Warning*: Failing to provide necessary information may cause the issue to be closed without consideration

### I found this bug / would like to have this new functionality
Code run into an error when HTML longer than A4 format error stack below.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPDF version 8.0 installed by composer. Using under laravel 5.8.

### This is a PHP code snippet I use

```
<?php
Controller function return with PDF download

/* $html (generated by laravel 5.8) */
$html  = view('template_name', $params :array)->render();

$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML($html);
return $mpdf->Output('filename.pdf', \Mpdf\Output\Destination::DOWNLOAD);
```

### This is a HTML/CSS code snippet I use

```
Cannot provide HTML because of the confidentiality agreement.
```

### Error stack
[2019-11-13 11:54:00] local.ERROR: Undefined index: current {"userId":6,"exception":"[object] (ErrorException(code: 0): Undefined index: current at vendor\\mpdf\\mpdf\\src\\Tag\\BlockTag.php:316)
[stacktrace]
#0 vendor\\mpdf\\mpdf\\src\\Tag\\BlockTag.php(316): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', 'G:\\\\workspace\\\\sp...', 316, Array)
#1 vendor\\mpdf\\mpdf\\src\\Tag.php(243): Mpdf\\Tag\\BlockTag->open(Array, Array, 177)
#2 vendor\\mpdf\\mpdf\\src\\Mpdf.php(13603): Mpdf\\Tag->OpenTag('P', Array, Array, 177)

### Fix
I fixed the problem with an isset() on 'current' index at the local enviroment.

**Comment by finwe** [comment] 2019-11-13 12:45
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a **HTML code example** to reproduce the issue.

**Closed by finwe** 2019-11-13 12:45 UTC

**Comment by parinithamanohar** [comment] 2021-07-24 11:51
> > Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> > For contributing here, please see the guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
> > _Warning_: Failing to provide necessary information may cause the issue to be closed without consideration
> 
> ### I found this bug / would like to have this new functionality
> Code run into an error when HTML longer than A4 format error stack below.
> 
> ### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
> mPDF version 8.0 installed by composer. Using under laravel 5.8.
> 
> ### This is a PHP code snippet I use
> ```
> <?php
> Controller function return with PDF download
> 
> /* $html (generated by laravel 5.8) */
> $html  = view('template_name', $params :array)->render();
> 
> $mpdf = new \Mpdf\Mpdf();
> $mpdf->WriteHTML($html);
> return $mpdf->Output('filename.pdf', \Mpdf\Output\Destination::DOWNLOAD);
> ```
> 
> ### This is a HTML/CSS code snippet I use
> ```
> Cannot provide HTML because of the confidentiality agreement.
> ```
> 
> ### Error stack
> [2019-11-13 11:54:00] local.ERROR: Undefined index: current {"userId":6,"exception":"[object] (ErrorException(code: 0): Undefined index: current at vendor\mpdf\mpdf\src\Tag\BlockTag.php:316)
> [stacktrace]
> #0 vendor\mpdf\mpdf\src\Tag\BlockTag.php(316): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', 'G:\\workspace\\sp...', 316, Array)
> #1 vendor\mpdf\mpdf\src\Tag.php(243): Mpdf\Tag\BlockTag->open(Array, Array, 177)
> #2 vendor\mpdf\mpdf\src\Mpdf.php(13603): Mpdf\Tag->OpenTag('P', Array, Array, 177)
> 
> ### Fix
> I fixed the problem with an isset() on 'current' index at the local enviroment.

isset() really worked!! thank you...

**Comment by Klap-in** [comment] 2021-07-24 22:08
Please share a (small as possible) example of your html and php config. (That is helpful to confirm the issue is completely fixed and the example is added to the test suite of mpdf). Adding such examples could speed up fixing of these kind of issues.

**Comment by parinithamanohar** [comment] 2021-07-26 03:59
> Please share a (small as possible) example of your html and php config. (That is helpful to confirm the issue is completely fixed and the example is added to the test suite of mpdf). Adding such examples could speed up fixing of these kind of issues.

in BlockTag.php - line 316 -elseif ($this->mpdf->page_box['current'] != $pagesel) { - if this was the line then you have to add
isset by foollowing way
elseif (isset($this->mpdf->page_box['current']) != $pagesel) {

**Comment by finwe** [comment] 2021-07-26 06:01
This is a closed issue. If you are experiencing problems in the latest version, create a new issue from an appropriate issue template.
