### ISSUE TITLE
Tel: url link is not working in pdf

### ISSUE THREAD

**Issue by kama777** [mpdf/mpdf#580] opened 2017-12-07 21:47 UTC
I cant seem to get mPDF links to work for phone numbers

I have tried adding this telephone link to pdf
`<a href='tel:12223334444'> Call Now (222) 333-4444 </a>`

But no luck, mpdf is showing `about:///#page1`  in iphone

What is the correct way of specifying a telephone link in mpdf or is this a bug.
Thanks

**Comment by fglueck** [comment] 2018-01-08 16:00
The Code to do this is:
`if (preg_match('@^(mailto|tel|fax):.*@i', $path)) {
`
But it works not in all PDF viewers, in FF not, on my Mobil it works fine in a old version of mpdf actuelly there is no code change on this part. Is there any changes after this?

**Comment by finwe** [comment] 2018-01-08 21:14
@kama777 What is your PDF viewer? On what platform?
@fglueck No, there has not been any change to this code portion since your PR.

**Comment by canhtran10** [comment] 2018-11-02 07:45
@fglueck Has your problem been resolved?
I have the same issue.

**Comment by MatthiasKuehneEllerhold** [comment] 2018-11-02 09:13
Using `ImportPage` destroys all kinds of links. See #900

**Comment by pocketcat** [comment] 2019-03-05 22:22
@kama777, did you find a solution for this? I'm having the same issue. Thanks!

**Comment by finwe** [comment] 2019-03-06 07:49
Closing as a duplicate of #900

**Closed by finwe** 2019-03-06 07:49 UTC
Labels: bug/fix

**Comment by lijogeorge** [comment] 2020-11-12 17:28
Try put a .(dot) anywhere in the href value. For example:
<a href="tel:+91.9876543210">Call +91-987-654-3210</a>

**Comment by fglueck** [comment] 2021-02-05 15:46
What is happend when putting a dot in the phonenumber?

**Comment by Dxg125** [comment] 2021-09-28 09:12
If you look at the regex you see that the dot is queried verbatim, which actually makes no sense.

However, if you specify the dot in the phone number, the link is created correctly and displayed in the PDF (with a dot in it, of course :/ ).

without dot it creates something like: [{"num":1,"gen":0},{"name":"XYZ"},0,841.89,null]

ty to @lijogeorge you saved me some hours :)

**Comment by krisjcallender** [comment] 2025-07-26 17:41
@finwe This issue should be reopened - there is certainly a bug here - it's nothing to do with ImportPage.
Placing a .(dot) into the link registers it as a hyperlink in the PDF however this extra dot ruins the functionality. See above.

**Comment by finwe** [comment] 2025-07-27 07:02
Create a separate issue with all required details, thanks.
