### ISSUE TITLE
Undefined indexes T, R, B, and L in CssManager when !important part of CSS rule

### ISSUE THREAD

**Issue by cliffordp** [mpdf/mpdf#1009] opened 2019-03-29 21:02 UTC
### I found this bug

Related to https://github.com/mpdf/mpdf/issues/524

**`\Mpdf\CssManager::expand24()` returns empty array when `!important` is part of the CSS rule, which causes these PHP notices:**

```
PHP Notice:  Undefined index: T in .../vendor/mpdf/mpdf/src/CssManager.php on line 729
PHP Stack trace:
PHP   ...
PHP  11. Mpdf\Mpdf->WriteHTML($html = *uninitialized*, $mode = *uninitialized*, $init = *uninitialized*, $close = *uninitialized*)
PHP  12. Mpdf\Tag->OpenTag($tag = *uninitialized*, $attr = *uninitialized*, $ahtml = *uninitialized*, $ihtml = *uninitialized*) .../vendor/mpdf/mpdf/src/Mpdf.php:13599
PHP  13. Mpdf\Tag\H2->open($attr = *uninitialized*, $ahtml = *uninitialized*, $ihtml = *uninitialized*) .../vendor/mpdf/mpdf/src/Tag.php:243
PHP  14. Mpdf\CssManager->PreviewBlockCSS($tag = *uninitialized*, $attr = *uninitialized*) .../vendor/mpdf/mpdf/src/Tag/BlockTag.php:37
PHP  15. Mpdf\CssManager->readInlineCSS($html = *uninitialized*) .../vendor/mpdf/mpdf/src/CssManager.php:2172
PHP  16. Mpdf\CssManager->fixCSS($prop = *uninitialized*) .../vendor/mpdf/mpdf/src/CssManager.php:514

PHP Notice:  Undefined index: R in .../vendor/mpdf/mpdf/src/CssManager.php on line 730
PHP Stack trace:
PHP   ...
PHP  11. Mpdf\Mpdf->WriteHTML($html = *uninitialized*, $mode = *uninitialized*, $init = *uninitialized*, $close = *uninitialized*)
PHP  12. Mpdf\Tag->OpenTag($tag = *uninitialized*, $attr = *uninitialized*, $ahtml = *uninitialized*, $ihtml = *uninitialized*) .../vendor/mpdf/mpdf/src/Mpdf.php:13599
PHP  13. Mpdf\Tag\H2->open($attr = *uninitialized*, $ahtml = *uninitialized*, $ihtml = *uninitialized*) .../vendor/mpdf/mpdf/src/Tag.php:243
PHP  14. Mpdf\CssManager->PreviewBlockCSS($tag = *uninitialized*, $attr = *uninitialized*) .../vendor/mpdf/mpdf/src/Tag/BlockTag.php:37
PHP  15. Mpdf\CssManager->readInlineCSS($html = *uninitialized*) .../vendor/mpdf/mpdf/src/CssManager.php:2172
PHP  16. Mpdf\CssManager->fixCSS($prop = *uninitialized*) .../vendor/mpdf/mpdf/src/CssManager.php:514

PHP Notice:  Undefined index: B in .../vendor/mpdf/mpdf/src/CssManager.php on line 731
PHP Stack trace:
PHP   ...
PHP  11. Mpdf\Mpdf->WriteHTML($html = *uninitialized*, $mode = *uninitialized*, $init = *uninitialized*, $close = *uninitialized*)
PHP  12. Mpdf\Tag->OpenTag($tag = *uninitialized*, $attr = *uninitialized*, $ahtml = *uninitialized*, $ihtml = *uninitialized*) .../vendor/mpdf/mpdf/src/Mpdf.php:13599
PHP  13. Mpdf\Tag\H2->open($attr = *uninitialized*, $ahtml = *uninitialized*, $ihtml = *uninitialized*) .../vendor/mpdf/mpdf/src/Tag.php:243
PHP  14. Mpdf\CssManager->PreviewBlockCSS($tag = *uninitialized*, $attr = *uninitialized*) .../vendor/mpdf/mpdf/src/Tag/BlockTag.php:37
PHP  15. Mpdf\CssManager->readInlineCSS($html = *uninitialized*) .../vendor/mpdf/mpdf/src/CssManager.php:2172
PHP  16. Mpdf\CssManager->fixCSS($prop = *uninitialized*) .../vendor/mpdf/mpdf/src/CssManager.php:514

PHP Notice:  Undefined index: L in .../vendor/mpdf/mpdf/src/CssManager.php on line 732
PHP Stack trace:
PHP   ...
PHP  11. Mpdf\Mpdf->WriteHTML($html = *uninitialized*, $mode = *uninitialized*, $init = *uninitialized*, $close = *uninitialized*)
PHP  12. Mpdf\Tag->OpenTag($tag = *uninitialized*, $attr = *uninitialized*, $ahtml = *uninitialized*, $ihtml = *uninitialized*) .../vendor/mpdf/mpdf/src/Mpdf.php:13599
PHP  13. Mpdf\Tag\H2->open($attr = *uninitialized*, $ahtml = *uninitialized*, $ihtml = *uninitialized*) .../vendor/mpdf/mpdf/src/Tag.php:243
PHP  14. Mpdf\CssManager->PreviewBlockCSS($tag = *uninitialized*, $attr = *uninitialized*) .../vendor/mpdf/mpdf/src/Tag/BlockTag.php:37
PHP  15. Mpdf\CssManager->readInlineCSS($html = *uninitialized*) .../vendor/mpdf/mpdf/src/CssManager.php:2172
PHP  16. Mpdf\CssManager->fixCSS($prop = *uninitialized*) .../vendor/mpdf/mpdf/src/CssManager.php:514
```

### This is mPDF 8.0.0, PHP version 7.2.0, and Apache

![image](https://user-images.githubusercontent.com/1812179/55262377-a5387700-523b-11e9-88a7-ce9cc45a9999.png)

### This is a PHP code snippet I use

```
$mpdf_args = [
	'mode'   => 'c',
	'format' => 'LETTER', // Default is A4
];
```

**Comment by finwe** [comment] 2019-03-29 21:12
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a **textual HTML/CSS** code example to reproduce the issue more easily.

**Comment by cliffordp** [comment] 2019-03-29 22:26
@finwe Please reopen with this additional information:

HTML sent to mPDF is attached here.
[cliff-important-5aef71f981481309526344.txt](https://github.com/mpdf/mpdf/files/3024745/cliff-important-5aef71f981481309526344.txt)

The HTML gets generated by this CSS (which includes the `!important`): https://github.com/moderntribe/event-tickets/blob/4.10.1.2/src/views/tickets/email.php

**Comment by finwe** [comment] 2019-03-30 05:18
Thanks, better, but could you please share as little code as possible that demonstrates this behaviour? A test with the whole chunk takes over 15 seconds.

**Comment by ssieb** [comment] 2019-03-30 05:47
```
<?php 
require_once __DIR__ . '/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML('
<div style="padding: 0 0 0 0 !important"></div>
');
$output = $mpdf->output('', 'S');
?>

```
The problem is that the !important doesn't get removed before parsing by expand24().  That means there are 5 elements which doesn't match any of the cases.  This only happens when all 4 numbers are used.

**Comment by finwe** [comment] 2019-03-30 10:42
Cool, thanks. I get where the problem is, I just wanted to have a code for the test case.

**Closed** 2019-04-01 09:04 UTC
