### ISSUE TITLE
Problems with accents into PDF's table of contents 

### ISSUE THREAD

**Issue by m4ucoder** [mpdf/mpdf#671] opened 2018-03-03 07:26 UTC
I found this bug: accents into TOC are not correctly displayed into PDF document.
> How to reproduce : 
```
$mpdf = new \Mpdf\Mpdf();
$mpdf->h2bookmarks = array('H1' => 0);
$mpdf->WriteHTML("<h1>Title with accents: é</h1><p>more text here</p>");
```
> Expected result:
Pdf TOC displays: "Title with accents: é"
> Real result:
Pdf TOC displays: "Title with accents: **?**"

> A possible solution ( It worked for me, I'm not sure that this is the definitive solution):
In the class Tag (file src/Tag.php), in the line ~# 5700, I have replaced : 
`$objattr['CONTENT'] = $content;`
by:
`$objattr['CONTENT'] = utf8_encode($content);`

Hope this helps

**Comment by finwe** [comment] 2018-03-03 07:51
This was a solution in previous PR but broke TOC generating in other cases so it was denied https://github.com/mpdf/mpdf/pull/391

**Comment by finwe** [comment] 2018-03-03 07:52
Closing as duplicate of https://github.com/mpdf/mpdf/issues/439

**Closed by finwe** 2018-03-03 07:52 UTC
Labels: bug/fix
