### ISSUE TITLE
 Background-image in @page CSS selector hides footer

### ISSUE THREAD

**Issue by leonidas-o** [mpdf/mpdf#619] opened 2018-01-22 12:12 UTC
Updated some packages and now running on: 

centos 7
php 7.1.14
mpdf 7.0.3
invoiceplane 1.5.6

Using a background-image on `@page`
`background: url("https://mydomain.com/img/first_page.png");background-image-resize:6;` the footer is hidden by the image on all pages.
When I remove the background-image, the footer is visible in the generated pdf.

**Comment by leonidas-o** [comment] 2018-02-05 17:49
Am I the only one experiencing this issue?

With this snippet the footer is hidden:
```
    <style>

        @page {
            
            background: url("https://myshare.mydomain.com/img/second_page.png");
            background-image-resize:6;
        }

        @page :first {
            
            background: url("https://myshare.mydomain.com/img/first_page.png");
            background-image-resize:6;
            
        }

    </style>
```

When adding margins to it like:
```
    <style>

        @page {
            margin-top: 3.5cm;
            margin-bottom: 2.54cm;
            margin-left: 2cm;
            margin-right: 2cm;
            background: url("https://myshare.mydomain.com/img/second_page.png");
            background-image-resize:6;
        }

        @page :first {
            
            background: url("https://myshare.mydomain.com/img/first_page.png");
            background-image-resize:6;
            
        }

    </style>
```
The whole process of generating the pdf crashed and I get:
```
A PHP Error was encountered

Severity: Notice

Message: Undefined index: miw

Filename: src/Mpdf.php

Line Number: 20794

Backtrace:
...
```

As soon as I remove the margins, I can generate a pdf, but the footer is still hidden by the background image.
Looks like a bug to me, can someone help please?

**Comment by vishaltatva** [comment] 2018-04-04 12:12
@leonidas-o Have you tried by adding z-index

**Comment by leonidas-o** [comment] 2018-04-15 09:29
@vishaltatva  yes, I do have tried that as well, but it doesn't help

**Comment by finwe** [comment] 2018-04-15 09:34
Related https://github.com/mpdf/mpdf/issues/716

**Comment by vishaltatva** [comment] 2018-04-16 05:45
@leonidas-o .Can you try adding to `z-index : -1 !important;`  footer section

**Comment by fmuellerprevion** [comment] 2018-04-17 08:32
I tried setting the z-index with no luck - but I found a workaround! 
In my case, it was because I was using @page selector, to set the background image of the first page. I used the body selector instead, and after AddPage (from the second page), I added a blank white image as background (background-image: none did not work..). With that, I got it fixed for me!

**Comment by finwe** [comment] 2018-04-18 11:33
Duplicate of #583

**Closed by finwe** 2018-04-18 11:33 UTC
