### ISSUE TITLE
MPDF page number in HTML

### ISSUE THREAD

**Issue by ghost** [mpdf/mpdf#172] opened 2016-07-06 13:54 UTC
Hello,

Currently I'm creating a template system, and we are using MPDF to generate the PDF versions of the templates, so far this has been great. But the only problem that we are having is that the page numbering tags do not get replaced in the WriteHTML block, but this is something that we would like to have. Is it in any way possible to get this working with a setting that I have missed?

Bob

**Comment by finwe** [comment] 2016-07-06 14:05
The Issue template is not here for nothing. Provide [a minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve) for your usecase, including your setup and library versions.

**Comment by finwe** [comment] 2016-07-10 07:46
Feel free to reopen with the additional information.

**Comment by jochenwezel** [comment] 2019-04-09 12:21
## I assume some reproduction code as following
```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML('Page {PAGENO} of {nb}');
$mpdf->Output();
?>
```

Current output:
```
Page {PAGENO} of {nb}
```

Requested output:
```
Page 1 of 1
```

## Solved with MPDF 6.1 as following
Changed function _puthtmlheaders() in mpdf.php: Added code block "Replace page no and total pages number variables in body of every page"

```php
                                }
                                /* -- FORMS -- */
                                foreach ($this->HTMLheaderPageForms AS $f) {
                                        $f['y'] += $adj;
                                        $this->mpdfform->forms[$f['n']] = $f;
                                }
                                /* -- END FORMS -- */
                        }

                        // Replace page no and total pages number variables in body of every page
                        $this->pages[$n] = str_replace(mb_convert_encoding('{PAGENO}', 'UTF-16', 'UTF-8'), mb_convert_encoding($pnstr, 'UTF-16', 'UTF-8'), $this->pages[$n]);
                        $this->pages[$n] = str_replace(mb_convert_encoding($this->aliasNbPgGp, 'UTF-16', 'UTF-8'), mb_convert_encoding($pntstr, 'UTF-16', 'UTF-8'), $this->pages[$n]); // {nbpg}
                        $this->pages[$n] = str_replace(mb_convert_encoding($this->aliasNbPg, 'UTF-16', 'UTF-8'), mb_convert_encoding($nb, 'UTF-16', 'UTF-8'), $this->pages[$n]); // {nb}

                }
                $this->page = $nb;
                $this->state = 1;
        }
```

**Comment by finwe** [comment] 2019-04-09 12:34
This is intended and documented behaviour. Page patterns are being replaced in headers and footers only.

**Comment by jochenwezel** [comment] 2019-04-09 12:49
The requested behavious is (at least from my side) to support it in body, too.
An "intendation" that this must not happen in body wouldn't be understandable.

**Comment by martijnpieters** [comment] 2019-07-15 09:50
I'd also like to have the feature as proposed by @jochenwezel.

@finwe Should I open a PR with the above mentioned solution, or is there a serious blocker over here (based on the `help wanted` label)?

**Comment by davidvanvan** [comment] 2019-09-11 08:00
any update on this possible feature? I am actually using his sulotion

**Comment by davidvanvan** [comment] 2019-09-11 08:19
> I'd also like to have the feature as proposed by @jochenwezel.
> 
> @finwe Should I open a PR with the above mentioned solution, or is there a serious blocker over here (based on the `help wanted` label)?

Have you created a PR good sir? I think this feature proposed by @jochenwezel is great

**Comment by jochenwezel** [comment] 2019-09-11 10:00
I solved it in my environment in mpdf.php in `function _puthtmlheaders()` with following code (approx. line 9728). If somebody could review it (especially for right version) and create a patch for for this ticket, I'd appreciate it :-)
```php
<?php

// ******************************************************************************
// Software: mPDF, Unicode-HTML Free PDF generator                              *
// Version:  6.1        based on                                                *
//           FPDF by Olivier PLATHEY                                            *
//           HTML2FPDF by Renato Coelho                                         *
// Date:     2016-03-25                                                         *
...
						$by = $this->w - $ax;
						$lk[0] = $bx * _MPDFK;
						$lk[1] = ($this->h - $by) * _MPDFK - $lw;
					}
					$this->PageLinks[$n][] = $lk;
				}
				/* -- FORMS -- */
				foreach ($this->HTMLheaderPageForms AS $f) {
					$f['y'] += $adj;
					$this->mpdfform->forms[$f['n']] = $f;
				}
				/* -- END FORMS -- */
			}
			
			// Customization for https://github.com/mpdf/mpdf/issues/172
                        // Replace page no and total pages number variables in body of every page
                        $this->pages[$n] = str_replace(mb_convert_encoding('{PAGENO}', 'UTF-16', 'UTF-8'), mb_convert_encoding($pnstr, 'UTF-16', 'UTF-8'), $this->pages[$n]);
                        $this->pages[$n] = str_replace(mb_convert_encoding($this->aliasNbPgGp, 'UTF-16', 'UTF-8'), mb_convert_encoding($pntstr, 'UTF-16', 'UTF-8'), $this->pages[$n]); // {nbpg}
                        $this->pages[$n] = str_replace(mb_convert_encoding($this->aliasNbPg, 'UTF-16', 'UTF-8'), mb_convert_encoding($nb, 'UTF-16', 'UTF-8'), $this->pages[$n]); // {nb}
			// /Customization for https://github.com/mpdf/mpdf/issues/172

		}
		$this->page = $nb;
		$this->state = 1;
	}

	function _putpages()
	{
		$nb = $this->page;
		$filter = ($this->compress) ? '/Filter /FlateDecode ' : '';
...
```

**Comment by nicklongo** [comment] 2019-10-02 09:31
Sorry @jochenwezel but your solution doesn't work in my mpdf.php (Version 7)

in this version _putpages() function is replaced by writePages() function in PageWriter.php .

Maybe the problem is not there, but after adding your  
```
// Customization for https://github.com/mpdf/mpdf/issues/172
                        // Replace page no and total pages number variables in body of every page
                        $this->pages[$n] = str_replace(mb_convert_encoding('{PAGENO}', 'UTF-16', 'UTF-8'), mb_convert_encoding($pnstr, 'UTF-16', 'UTF-8'), $this->pages[$n]);
                        $this->pages[$n] = str_replace(mb_convert_encoding($this->aliasNbPgGp, 'UTF-16', 'UTF-8'), mb_convert_encoding($pntstr, 'UTF-16', 'UTF-8'), $this->pages[$n]); // {nbpg}
                        $this->pages[$n] = str_replace(mb_convert_encoding($this->aliasNbPg, 'UTF-16', 'UTF-8'), mb_convert_encoding($nb, 'UTF-16', 'UTF-8'), $this->pages[$n]); // {nb}
			// /Customization for https://github.com/mpdf/mpdf/issues/172
```
in mpdf.php file, and after upload file on server, {nb} or {PAGENO} or {nbpg} remain in the "String" mode.

Could you please tell me what could be wrong with Mpdf 7?

**Comment by jochenwezel** [comment] 2019-10-02 16:17
Since Mpdf.php of v7 has been redesigned completely, I can’t quickly find the missing piece.
I solved it by stepping through the code with some debugging and finally found a code location to fix it.

Von: nicklongo <notifications@github.com>
Gesendet: Mittwoch, 2. Oktober 2019 11:31
An: mpdf/mpdf <mpdf@noreply.github.com>
Cc: Jochen Wezel - CompuMaster GmbH <jwezel@compumaster.de>; Mention <mention@noreply.github.com>
Betreff: Re: [mpdf/mpdf] MPDF page number in HTML (#172)


Sorry @jochenwezel<https://github.com/jochenwezel> but your solution doesn't work in my mpdf.php (Version 7)

in this version _putpages() function is replaced by writePages() function in PageWriter.php .

Maybe the problem is not there, but after adding your

// Customization for https://github.com/mpdf/mpdf/issues/172

                        // Replace page no and total pages number variables in body of every page

                        $this->pages[$n] = str_replace(mb_convert_encoding('{PAGENO}', 'UTF-16', 'UTF-8'), mb_convert_encoding($pnstr, 'UTF-16', 'UTF-8'), $this->pages[$n]);

                        $this->pages[$n] = str_replace(mb_convert_encoding($this->aliasNbPgGp, 'UTF-16', 'UTF-8'), mb_convert_encoding($pntstr, 'UTF-16', 'UTF-8'), $this->pages[$n]); // {nbpg}

                        $this->pages[$n] = str_replace(mb_convert_encoding($this->aliasNbPg, 'UTF-16', 'UTF-8'), mb_convert_encoding($nb, 'UTF-16', 'UTF-8'), $this->pages[$n]); // {nb}

                       // /Customization for https://github.com/mpdf/mpdf/issues/172

in mpdf.php file, and after upload file on server, {nb} or {PAGENO} or {nbpg} remain in the "String" mode.

Could you please tell me what could be wrong with Mpdf 7?

**Comment by fsmalaquias** [comment] 2020-06-06 16:14
Any update ?

**Comment by finwe** [comment] 2022-04-05 19:57
Closing as resolved in mentioned issue.

**Closed by finwe** 2022-04-05 19:57 UTC
Labels: feature/enhancement, help wanted
