### ISSUE TITLE
& in imagename -> mpdf crashes

### ISSUE THREAD

**Issue by dreaddy** [mpdf/mpdf#1050] opened 2019-06-24 19:35 UTC
Hi, im including some images in my pdf with & in the uri (generated from another PHP Script).

For example
http://localhost/?p=ajax&ajaxCall=1&command=getSignatureImage&sigauth=123mf9843fj3m49f93284mf89fj4mmfmgnghbrfv&appointmentId=12

mpdf tries to fopen a Version of the path with & a m p ; instead of & and crashes.

For me, adding file_exists to src\Image\ImageProcessor.php Line 220 did the trick:

```
/*added file exist check to prevent error*/
 if(file_exists($orig_srcpath)){
                if ($orig_srcpath && $this->mpdf->basepathIsLocal && $check = fopen($orig_srcpath, 'rb')) {
                    fclose($check);
                    $file = $orig_srcpath;
                    $this->logger->debug(sprintf('Fetching (file_get_contents) content of file "%s" with local basepath', $file), ['context' => LogContext::REMOTE_CONTENT]);
                    $data = file_get_contents($file);
                    $type = $this->guesser->guess($data);
                }
            }

            /*added file exist check to prevent error*/
            if(file_exists($file)){
                if (!$data && $check = @fopen($file, 'rb')) {
                    fclose($check);
                    $this->logger->debug(sprintf('Fetching (file_get_contents) content of file "%s" with non-local basepath', $file), ['context' => LogContext::REMOTE_CONTENT]);
                    $data = file_get_contents($file);
                    $type = $this->guesser->guess($data);
                }
            }
```

Error:

Fatal error: Uncaught Mpdf\MpdfException: Error detected. PDF file generation aborted: fopen(https://localhost/?p=ajax&amp;ajaxCall=1&amp;command=getSignatureImage&amp;sigauth=123mf9843fj3m49f93284mf89fj4mmfmgnghbrfv&amp;appointmentId=19): failed to open stream: operation failed in D:\work\abdu\stundenerfassung\srv\htdocs\vendor\mpdf\mpdf\src\Image\ImageProcessor.php:231 Stack trace: #0 D:\work\abdu\stundenerfassung\srv\htdocs\apps\erfolgspfad\mvc\controls\eventmanagerControl.inc.php(174): Mpdf\Mpdf->Output('Erfolgspfad Unt...', 'I') #1 D:\work\abdu\stundenerfassung\srv\htdocs\bpfw\mvc\controls\defaultcontrol.inc.php(94): EventmanagerControl->handleAjaxCommand('generatePdf') #2 D:\work\abdu\stundenerfassung\srv\htdocs\bpfw\mvc\controlhandler.php(88): DefaultControl->handleActions() #3 D:\work\abdu\stundenerfassung\srv\htdocs\bpfw\pages.php(56): ControlHandler->createControlAfterModelCreation(Object(EventmanagerModel)) #4 D:\work\abdu\stundenerfassung\srv\htdocs\index.php(98): require_once('D:\\work\\abdu\\st...') #5 {main in D:\work\abdu\stundenerfassung\srv\htdocs\vendor\mpdf\mpdf\src\Image\ImageProcessor.php on line 231

**Comment by finwe** [comment] 2019-06-24 20:02
Not really helpful. That issue template is not there for nothing, you know. How do you initialize the Mpdf object? Can you share a small HTML snippet reproducing this behaviour?

**Comment by dreaddy** [comment] 2019-06-25 01:28
Generating a pdf from the html

`<img src="http://localhost/?p=ajax&ajaxCall=1&command=getSignatureImage&sigauth=123mf9843fj3m49f93284mf89fj4mmfmgnghbrfv&appointmentId=12" >`

should do to reproduce the error.

The $orig_srcpath Variable in ImageProcessor.php then contains "https://localhost/?p=ajax&amp;ajaxCall=1&amp;command=getSignatureImage&amp;sigauth=123mf9843fj3m49f93284mf89fj4mmfmgnghbrfv&amp;appointmentId=19" I think thats the error. 

---

current mpdf Settings:

```
$defaultConfig = (new Mpdf\Config\ConfigVariables())->getDefaults();

$mpdf = new \Mpdf\Mpdf(
[

   'margin_left' => 20,
   'margin_right' => 15,
   'margin_top' => 35,
   'margin_bottom' => 25,
   'margin_header' => 10,
   'margin_footer' => 10,
]

);


$mpdf->showImageErrors = true;

$mpdf->curlAllowUnsafeSslRequests = true;

$mpdf->SetTitle("Erfolgspfad");
$mpdf->SetAuthor("Erfolgspfad");
$mpdf->debugfonts = false;
$mpdf->debug = true;

$mpdf->SetDisplayMode('fullpage');
```

**Comment by fglueck** [comment] 2019-06-25 07:15
Did you try 
`fopen("https://localhost/?p=ajax&amp;ajaxCall=1&amp;command=getSignatureImage&amp;sigauth=123mf9843fj3m49f93284mf89fj4mmfmgnghbrfv&amp;appointmentId=19"):
`
without mpdf?
I think it is not a problem of mpdf, I use mpdf a lot of years with local an remote images wich are generated by php with a lot of parameters and it works like perfect.

**Comment by finwe** [comment] 2019-06-25 07:32
Unable to reproduce, closing. Image path with ampersands works OK, even when ampersands are encoded to HTML entities.

**Closed by finwe** 2019-06-25 07:32 UTC
Labels: bug/fix, research needed
