### ISSUE TITLE
Automatic Page Break for div

### ISSUE THREAD

**Issue by db-dzine** [mpdf/mpdf#447] opened 2017-07-19 09:49 UTC
### These are mPDF and PHP versions I am using
MPDF 6.1

Is there any way to automatically break divs if they do not fit 100% to one page?

**Comment by finwe** [comment] 2018-08-28 16:14
Closing as HTML/PHP code to reproduce the issue is missing. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to easier reproduce the issue.

**Closed by finwe** 2018-08-28 16:14 UTC
Labels: missing sample / test, wontfix
