### ISSUE TITLE
Division by zero mpdf/mpdf.php Line: 15009

### ISSUE THREAD

**Issue by wafiamustafa** [mpdf/mpdf#296] opened 2016-12-28 11:53 UTC
### This is a PHP code snippet I use

```
<?php

$mpdf = new mPDF('', 'A4', '', '', 20, 20, 25, 25, 18, 8);
$mpdf->defaultfooterline = 0;
$mpdf->debug = true;
$footer = '<table width="100%">
    <tr>
    <td width="70%" style="color: #000000; padding-bottom:0px; margin-bottom:0px; vertical-align: bottom; font-family: Arial; font-size: 10px; text-align:left;border-bottom:1px dotted #000">Tenant Signed: '.$_POST['tenant_signed'].'</td><td style="color: #000000 ; text-align: left; vertical-align: bottom;  padding-bottom:0px; margin-bottom:0px;  font-family: Arial; font-size: 10px; border-bottom:1px dotted #000"> Dated: '.$agreement_datef.'</td>
    </tr>
    </table>';
$mpdf->SetFooter($footer);
$mpdf->DefHTMLFooterByName('Chapter2Footer', '<div style="text-align: right; vertical-align:top; font-weight: bold; font-size: 7pt; font-style: italic;">Chapter 2 Footer</div>');
$mpdf->SetDisplayMode('fullpage');
$mpdf->WriteHTML($html);
$fiepath = 'pdffiles/tenancy-'.$last_id. date('YmdHis') . '.pdf';
$fiepath1 = 'pdffiles/tenancy-'.$last_id. date('YmdHis') . '.docx';
$mpdf->Output('../'.$fiepath, 'F');

```

### This is a HTML code snippet I use

```

```

**Comment by finwe** [comment] 2017-03-09 15:19
Closing, unable to reporoduce in 7.0-beta

**Closed by finwe** 2017-03-09 15:19 UTC

**Comment by LewisWBPD** [comment] 2017-07-24 12:06
For anyone else having this problem, it was caused for us because we had SVGs that had been saved using Adobe Illustrator's "Preserve editing abilities" setting enabled. This caused the SVG to contain invalid XML (`&ns_ai;` attributes) which MPDF failed to parse and just set the width/height of the image as 0. [Here is some more info on cleaning the SVG so it works](https://commons.wikimedia.org/wiki/User:Quibik/Cleaning_up_SVG_files_manually#Editing).

Looking at the latest code I suspect the issue is still present in 7.0. It's not so-much an issue with MPDF because of the broken XML, but maybe we could introduce a check for parsing errors after parsing the SVG's XML.

**Comment by zackphilipps** [comment] 2018-02-27 23:25
I'm getting this error and I'm not even using SVGs...

**Comment by finwe** [comment] 2018-02-27 23:51
@zackphilipps You are not helpful in fixing this. What about providing a code sample?

**Comment by zackphilipps** [comment] 2018-02-28 03:38
@finwe Sorry, this is just really frustrating. In my case, this has nothing to do with the code; it's the environment. The exact same template works on live, just not on my local. So it's a problem with missing assets, file permissions, SSL cert config, or some combination of the three. I'm still investigating and will report back once I know more.

However, regarding images specifically, it seems like 9 times out of 10 the error message doesn't reflect the actual error that's occurring. I'm using 6.1; hopefully this has been improved in more recent versions.

**Comment by zackphilipps** [comment] 2018-02-28 16:24
@finwe So, I got this error after adding this line to my `php.ini` to fix the invalid cert problem:

```
curl.cainfo = "/etc/apache2/ssl/apache.crt"
```

But, let's say the image in question is called `image1.jpg`. This file actually didn't exist in the filesystem, so I should've gotten the standard "**Fatal error:** Uncaught MpdfException: IMAGE Error (`image1.jpg`): Could not find image file." Right?

Prior to adding that line, I DID get "**Fatal error:** Uncaught MpdfException: IMAGE Error (`image2.jpg`): Could not find image file," only here's the rub: `image2.jpg` actually DID exist in the filesystem, and this was actually an invalid cert error.
