### ISSUE TITLE
mpdf and Mathjax: Example displayed in Documentation doesn't work.

### ISSUE THREAD

**Issue by raul93611** [mpdf/mpdf#1240] opened 2020-06-05 01:14 UTC
### I am using this code which is almost the same code of the example:

```
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
// You should include a check for unwanted external referrers to prevent
// calls on this script from external websites!
require_once __DIR__ . '/vendor/autoload.php';
$mpdf = new \Mpdf\Mpdf();

$html = $_POST['bodydata'];
$html = urldecode($html);

preg_match('/<svg[^>]*>\s*(<defs.*?>.*?<\/defs>)\s*<\/svg>/', $html, $m);
$defs = $m[1];
$html = preg_replace('/<svg[^>]*>\s*<defs.*?<\/defs>\s*<\/svg>/', '', $html);
$html = preg_replace('/(<svg[^>]*>)/', "\\1".$defs, $html);
preg_match_all('/<svg([^>]*)style="(.*?)"/', $html, $m);

for ($i = 0; $i < count($m[0]); $i++) {
    $style = $m[2][$i];

    preg_match('/width: (.*?);/',$style, $wr);
    $w = $mpdf->ConvertSize($wr[1], 0, $mpdf->FontSize) * $mpdf->dpi/25.4;

    preg_match('/height: (.*?);/',$style, $hr);
    $h = $mpdf->ConvertSize($hr[1], 0, $mpdf->FontSize) * $mpdf->dpi/25.4;

    $replace = '<svg'.$m[1][$i].' width="'.$w.'" height="'.$h.'" style="'.$m[2][$i].'"';
    $html = str_replace($m[0][$i], $replace, $html);
}

$stylesheet = '
/* This helps alignment for inline equations */
img {
    vertical-align: middle;
}

/* This sets padding for display equations (but not in-line ones) */
.MathJax_SVG_Display {
    padding: 1em 0;
}

/* This prevents the Create PDF button being reproduced in the PDF document */
/* Use this method to suppress other parts of the web-page from displaying */
#mpdf-create {
    display: none;
}

/* Add any other CSS styling here for the rest of the document */
/* The CSS/stylesheet information from the original page is not accessible here */
';

$mpdf->WriteHTML($stylesheet,1);
$mpdf->WriteHTML($html);

$mpdf->Output();
exit;

```

### This is the HTML of the example

```
<!DOCTYPE html>
<html>
<head>
    <!-- This line adds MathJax to the page with default SVG output -->
    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_SVG"></script>
</head>
<body>
    <h3>The Cauchy-Schwarz Inequality (TeX)</h3>

    \[ \left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right) \]

    <h3>Standard Deviation (MathML)</h3>

    <math display="block"><mrow><mi>&amp;#x03c3;</mi><mo&ge;</mo><msqrt><mrow><mfrac><mrow><mn>1</mn></mrow><mrow><mi>N</mi></mrow></mfrac><mstyle displaystyle="true"><mrow><munderover><mrow><mo>&amp;#x2211;</mo></mrow><mrow><mi>i</mi><mo&ge;</mo><mn>1</mn></mrow><mrow><mi>N</mi></mrow></munderover><mrow><msup><mrow><mo stretchy="false">(</mo><msub><mrow><mi>x</mi></mrow><mrow><mi>i</mi></mrow></msub><mo>&amp;#x2212;</mo><mi>&amp;#x03bc;</mi><mo stretchy="false">)</mo></mrow><mrow><mn>2</mn></mrow></msup></mrow></mrow></mstyle></mrow></msqrt><mo>.</mo></mrow></math>

    <h3>Inline equation (TeX)</h3>

    Finally, while display equations look good for a page of samples, the ability to mix math and text in a paragraph is
    also important. This expression \(\sqrt{3x-1}+(1+x)^2\) is an example of an inline equation.  As you see, MathJax
    equations can be used this way as well, without unduly disturbing the spacing between lines.

    <!-- This block of code adds a button to send the processed HTML code to your script: example_test.php -->

    <div id="mpdf-create">
        <form autocomplete="off" action="example_test.php" method="POST" id="pdfform" onSubmit="document.getElementById('bodydata').value=encodeURIComponent(document.body.innerHTML);">
        <input type="submit" value="PDF" name="submit"/>
        <input type="hidden" value="" id="bodydata" name="bodydata" />
        </form>
    </div>
</body>
</html>
```
### And I am getting this error

```
Notice: Undefined offset: 1 in /home/raul-new/Documentos/proyectos/pdf/example_test.php on line 23

Fatal error: Uncaught Mpdf\MpdfException: Call to undefined method Mpdf\Mpdf::ConvertSize() in /home/raul-new/Documentos/proyectos/pdf/vendor/mpdf/mpdf/src/Strict.php:15 Stack trace: #0 /home/raul-new/Documentos/proyectos/pdf/example_test.php(23): Mpdf\Mpdf->__call() #1 /home/raul-new/.composer/vendor/cpriego/valet-linux/server.php(232): require('/home/raul-new/...') #2 {main} thrown in /home/raul-new/Documentos/proyectos/pdf/vendor/mpdf/mpdf/src/Strict.php on line 15
```

**Comment by finwe** [comment] 2020-06-05 07:56
Duplicate of #596

**Closed by finwe** 2020-06-05 07:56 UTC
