### ISSUE TITLE
Invalid size representation "100mm!important"

### ISSUE THREAD

**Issue by kspal** [mpdf/mpdf#702] opened 2018-03-29 07:58 UTC
Hi,

I found this bug :

Fatal error: Uncaught exception 'Mpdf\MpdfException' with message 'Invalid size representation "100mm!important"' in /vendor/mpdf/mpdf/src/SizeConverter.php:36 
Stack trace:
 #0 /vendor/mpdf/mpdf/src/Tag/Table.php(472): Mpdf\SizeConverter->convert('100mm!important', 180.00155555556, 3.8805555555556, false) 
#1 /vendor/mpdf/mpdf/src/Tag.php(239): Mpdf\Tag\Table->open(Array, Array, 1) 
#2 /vendor/mpdf/mpdf/src/Mpdf.php(15310): Mpdf\Tag->OpenTag('TABLE', Array, Array, 1) 
#3 /testmpdf.php(29): Mpdf\Mpdf->WriteHTML('\r\n<!DOCTYPE htm...') 
#4 {main} thrown in /vendor/mpdf/mpdf/src/SizeConverter.php on line 36

I m using php7.2 and mpdf 7.0.3

### This is a PHP code snippet I use :
```
<?php
$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML($html);
$buffer=$mpdf->Output('test.pdf',\Mpdf\Output\Destination::DOWNLOAD); 
```

### This is a HTML/CSS code snippet I use
```
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
		<title>test</title>
	</head>
  <body>

    <table style="border:1mm solid #000000;width:100mm!important;">
      <tbody>
        <tr>
          <td>
            <strong>TEST1</strong>
          </td>   
        </tr>
      </tbody> 
    </table>
  </body>
</html>
```

**Comment by finwe** [comment] 2018-03-29 07:59
Duplicate of #524

**Closed by finwe** 2018-03-29 07:59 UTC
