### ISSUE TITLE
PHP 7.1 Warning: A non-numeric value encountered

### ISSUE THREAD

**Issue by deStrO** [mpdf/mpdf#302] opened 2017-01-08 20:34 UTC
### I have this problem/would like to have this functionality
When I try to render a PDF, I got this error:
Warning: A non-numeric value encountered

### These are mPDF and PHP versions I am using
PHP 7.1 with mpdf 6.1.3

in vendor\mpdf\mpdf\mpdf.php at line 30648 

I checked, the value of $this->dpi is null, tried to set on my own and it remains null
My only fix is to set $this->dpi to 96 in the ConvertSize function

**Comment by deStrO** [comment] 2017-01-08 20:38
Hum just saw that the root cause was the fact I used "auto" for my margins.

`margin: 0 auto;`

This was making the exception thrown

**Comment by finwe** [comment] 2017-01-09 06:55
Please see https://github.com/mpdf/mpdf/issues/300#issuecomment-271087459 - mPDF 6.x will not maintain PHP 7.1+ compatibility. That is the goal for mPDF 7.x, or the `development` branch.

Also see https://github.com/mpdf/mpdf/issues/294 which is a duplicate of this issue.

**Closed by finwe** 2017-01-09 06:55 UTC
Labels: duplicate, wontfix

**Comment by grishconner** [comment] 2017-05-16 06:56
Found solution here

[http://stackoverflow.com/questions/43994365/upgrade-to-php7-1-and-mpdf-show-error-a-non-numeric-value-encountered-at-line](url)
