### ISSUE TITLE
CSS right ignored in position absolute on development branch

### ISSUE THREAD

**Issue by thadin** [mpdf/mpdf#364] opened 2017-03-29 09:17 UTC
### I have this problem
In the development branch the CSS right variable doesn't seem to be parsed correctly.

### These are mPDF and PHP versions I am using
mPDF `dev-development 94bfea1` (latest)
PHP `7.1.3`

### This is a PHP code snippet I use
```php
<?php

$pdf = new Mpdf\Mpdf;

$html = <<<HTML
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Test PDF</title>
	<style type="text/css">
		.address { position: absolute; right: {$pdf->rMargin}mm; top: {$pdf->tMargin}mm; font-size: 0.9em; text-align: right; }
	</style>
</head>
<body>
	<div class="address">
		address-div
	</div>
	Normal text
</body>
</html>
HTML;

$pdf->WriteHTML($html);
$pdf->Output('Test.pdf', 'D');
```

Output in Mpdf 7:
![afbeelding](https://cloud.githubusercontent.com/assets/5312973/24447198/6a43ae04-1470-11e7-974a-674590d63c1a.png)

Output in mPDF 6.1.3:
![afbeelding](https://cloud.githubusercontent.com/assets/5312973/24447259/9c7dfc80-1470-11e7-9aa8-891fac971803.png)

I've verified the values of `$pdf->rMargin` & `$pdf->tMargin`, they're `15` & `16` respectively.

**Comment by finwe** [comment] 2017-03-29 09:39
This seems related to #353 - will fix.

**Comment by finwe** [comment] 2017-07-17 17:03
Closing as duplicate of #176

**Closed by finwe** 2017-07-17 17:03 UTC
Labels: bug/fix
