### ISSUE TITLE
Asking for password when open in google mail ( browser )

### ISSUE THREAD

**Issue by djambrosic** [mpdf/mpdf#173] opened 2016-07-07 10:01 UTC
protected function testPDF()
	{
		$html = '<!DOCTYPE html>
					<html lang="en">
					  <head>
						<meta charset="utf-8">
						<title>title</title>
					  </head>
					  <body>
						TEST
					  </body>
					</html>';
		$mpdf = new mPDF();
		$mpdf->SetProtection(array('copy','print', 'print-highres'),'', 1);
		$mpdf->WriteHTML($html);
		$mpdf->Output('TEST.pdf', 'D');
	}

When trying to open the PDF generated by the above code inside gmail's web interface (just attach to an email and send to your @gmail.com  ... then in https://mail.google.com/mail/ click to open, not download) you are asked for an open password, even though it is not set.
At first it looked like a problem in gmail as the PDF opens normally everywhere else, however we realized that a PDF with the same permissions created in LibreOffice for example works normally and opens without asking for password.

Opening a ticket here just in case its some minor incompatibility in the way encryption/permissions are done in mPDF.

mPDF version 6.1.1

**Comment by finwe** [comment] 2016-07-07 11:04
This is a duplicate of a 2 days old #171.

**Closed by finwe** 2016-07-07 11:04 UTC
