### ISSUE TITLE
OverWrite throws error: Deprecated: preg_match_all(): Passing null to parameter #2 ($subject) of type string is deprecated

### ISSUE THREAD

**Issue by nekromoff** [mpdf/mpdf#1770] opened 2022-12-05 23:10 UTC
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

```
$search = [
    '[XXX]',
    '[YYY]',
];

$replacement = [
    'Yes',
    'No',
];

$mpdf->OverWrite('template.pdf', $search, $replacement, 'F', 'output/test.pdf');
```

will throw an error:
```
Warning: Undefined array key 1 in ...../vendor/mpdf/mpdf/src/Mpdf.php on line 27233

Deprecated: preg_match_all(): Passing null to parameter #2 ($subject) of type string is deprecated
```

### mPDF version

8.1.2

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

Apache, PHP 8.1.12

### Reproducible PHP+CSS+HTML snippet suffering by the error

$search = [
    '[XXX]',
    '[YYY]',
];

$replacement = [
    'Yes',
    'No',
];

$mpdf->OverWrite('template.pdf', $search, $replacement, 'F', 'output/test.pdf');

**Comment by nekromoff** [comment] 2022-12-05 23:18
Probably this is related:
https://github.com/mpdf/mpdf/issues/626

**Comment by finwe** [comment] 2022-12-06 06:51
Probably, closing in favor of the original issue.

Duplicate of #626

**Closed by finwe** 2022-12-06 06:51 UTC
