### ISSUE TITLE
error 500 in function ouput() with PHP7

### ISSUE THREAD

**Issue by paddy2202** [mpdf/mpdf#263] opened 2016-11-10 07:04 UTC
### I have this problem/would like to have this functionality
(This is my first issue report on github)
When creating a PDF from HTML, I'm getting server error 500.
I've debugged the code to find out which part is reasonable for this.

The problem occurs when using the function `output('filename.pdf', 'D')`. In the switch case part, there are some header statements for the content-type starting in line 9428. Commenting out the 2nd, 3rd and 4th statement avoids the error 500:
```php
header('Content-Type: application/force-download');
//header('Content-Type: application/octet-stream', false);
//header('Content-Type: application/download', false);
//header('Content-Type: application/pdf', false);
```
### These are mPDF and PHP versions I am using
- mPDF 6
- PHP 7.0.6 (no problems with PHP 5.6)

### This is a PHP code snippet I use
-

### This is a HTML code snippet I use
-

**Comment by finwe** [comment] 2016-11-10 12:54
What is the error message?

**Comment by paddy2202** [comment] 2016-11-10 13:09
Sorry but there was no error message in the php error log. php.ini options for logging (log_errors = 1, error_log = 'path/to/my/log/) are set.
Displayed was only the http 500 error. So I tried with `exit();` which statement generates it and commented it out to succesfully get my PDF for download.

**Comment by finwe** [comment] 2016-11-10 13:30
If there is no PHP error message, then the error is not likely caused by PHP and therefore surely not by mPDF. Try looking for errors in server (Apache/nginx) error logs. Closing, feel free to reopen with additional information.

**Closed by finwe** 2016-11-10 13:30 UTC

**Comment by julianwinkel** [comment] 2016-11-20 22:40
It's a restriction by FastCGI. I have the same error. You can find the message in your apache_error.log

[Sun Nov 20 23:30:13 2016] [error] [client ::1] FastCGI: comm with server "/Applications/MAMP/fcgi-bin/php5.6.25.fcgi" aborted: error parsing headers: duplicate header 'Content-Type', referer: http://....

**Comment by paddy2202** [comment] 2016-11-22 09:23
Cool thanks :)
So I think mpdf should check php_sapi_name() for fastcgi to handle the output correctly.

**Comment by raphjutras** [comment] 2017-01-25 13:23
I have the same problem, I get an internal server error because FastCGI do not allow duplicate Content-type...  If the error is not caused by PHP, it means that PHP is too-permissive and mPDF should comply to RFC standards. It is bad practice to have duplicate content-type headers so prepare to get more and more error in the future caused by those duplicates.

---Error from logs---
[fastcgi:error] [pid 836:tid 140144640255744] [client 68.71.34.33:36180] FastCGI: comm with server "/var/www/php5-fpm/php5.external" aborted: error parsing headers: duplicate header 'Content-Type', referer: http://xxxxxxx

**Comment by finwe** [comment] 2017-01-25 14:45
can you please post what is the output of `php_sapi_name()` function on your machine? thanks!

**Comment by raphjutras** [comment] 2017-01-25 14:57
Sure, it's : "fpm-fcgi"

**Comment by finwe** [comment] 2017-01-25 15:01
Hm, not usable. I have the same (php 7.1 fpm in nginx) and have no duplicate headers error. What's your server?

**Comment by raphjutras** [comment] 2017-01-25 15:08
I'm hosting on clever-cloud so I don't have all that info, maybe this could help: (this is the actual config)
https://php70info.cleverapps.io/

**Comment by raphjutras** [comment] 2017-01-25 15:12
The HTTP server is Apache 2, and the PHP code is executed by PHP-FPM.

**Comment by finwe** [comment] 2017-01-30 20:54
Removed multiple HTTP Content-Type headers in `development` branch

**Comment by raphjutras** [comment] 2017-01-30 20:54
Nice!! @finwe
