### ISSUE TITLE
Inline styles that contain the !important rule cause a \Mpdf\MpdfException

### ISSUE THREAD

**Issue by craigdolphin** [mpdf/mpdf#695] opened 2018-03-21 21:16 UTC
### I found this bug
Inline styles that contain the !important rule cause a \Mpdf\MpdfException ('Invalid size representation') to be thrown on line 33 of /mpdf/mpdf/src/SizeConverter.php because the regex does not allow for the !important rule to exist

eg.
### This is a HTML/CSS code snippet I use
    <p style='margin-bottom: 0px!important;'>Test example</p>

This can be fixed by adding a line to remove the !important rule before the match is attempted in SizeConverter.php:

### For Example:
    $size = trim(strtolower($size));
    $size = str_replace('!important','',$size);
    $res = preg_match('/^(?P<size>[-0-9.,]+)?(?P<unit>[%a-z-]+)?$/', $size, $parts);

but it would probably be better if the regex could be modified to account for this possibility (beyond me I'm afraid)

Additionally, it would be better (IMO) if mPDF used a try/catch approach to calling the convert function in the setCSS function of the main Mpdf.php file so that any issues with malformed inline css do not block the creation of the document.

**Comment by finwe** [comment] 2018-03-22 08:34
Closing as duplicate of #524

**Closed by finwe** 2018-03-22 08:34 UTC
