### ISSUE TITLE
Invalid size representation

### ISSUE THREAD

**Issue by murraycollingwood** [mpdf/mpdf#687] opened 2018-03-13 21:07 UTC
Hello

Just updated to the latest stable version.
I've updated to use the new \Mpdf\Mpdf([...]) syntax.

The error message:
PHP Fatal error:  Uncaught exception 'Mpdf\MpdfException' with message 'Invalid size representation "expression(this.width  600 ? 600: true)"' in /home/sobs/vendor/mpdf/mpdf/src/SizeConverter.php:35

Actually I have two problems:
1. The above message doesn't tell me really where the original code is coming from - can it?
2. Is this a matter of having to modify the CSS or whether Mpdf should be handling this?

Versions: mPDF 7.0.3  PHP 5.6.33   Debian Linux

### This is a PHP code snippet I use
		$mpdf=new \Mpdf\Mpdf(['mode'=>'utf-8', 'format'=>'A4', 'orientation'=>'P', 'tempDir'=>'ztemp']);
		$mpdf->shrink_tables_to_fit = 1.6;
		$stylesheet = file_get_contents('style.css');
		$stylesheet .= "
			.blackback {
				color: black;
			}
			body {
				$prtfontsize
			}
			h1, h2 {
				color: black;
			}
			div { font-size: medium; }
			@media print {
				.keeptogether 	{ page-break-inside: avoid }
				.breakhere 		{ page-break-before: always }
			}";
		$mpdf->WriteHTML($stylesheet,1);
		$mpdf->SetHeader($headertext,2);
		$mpdf->WriteHTML($gen);
		$mpdf->Output($generalpdf, "F");

### This is a HTML/CSS code snippet I use
`<img src='$serverurl/$filename' style='max-width:600px; width: expression(this.width > 600 ? 600: true);' />`

Cheers
Murray

**Comment by ssieb** [comment] 2018-03-14 02:00
How is that valid?  What would "width: true" mean?

**Comment by murraycollingwood** [comment] 2018-03-14 02:08
Yes - very good point.
Perhaps it would be better as:
`<img src='$serverurl/$filename' style='max-width:600px; width: expression(this.width > 600 ? 600: auto);' />`

**Comment by finwe** [comment] 2018-03-14 08:07
mPDF does not support expressions in CSS and since 7.x is somewhat more restrictive about definitions it cannot process. Tagging as a bug, this should be simply ignored when unable to process.

**Comment by cheesegrits** [comment] 2018-03-15 16:17
@finwe 

I just found a similar issue with Bootstrap v2 CSS, which had a nasty IE7 hack in it that uses ...

width="auto\9"

I've hacked around it, and was going to submit a PR to handle it, but from your comment, it seems like you intend to stop throwing an exception on an invalid width, and just ignore it?

if so, I'll just go with my local hack, and wait for the official "ignore it" fix.

**Comment by finwe** [comment] 2018-03-22 08:34
Closing as duplicate of #524

**Closed by finwe** 2018-03-22 08:34 UTC
Labels: bug/fix
