### ISSUE TITLE
I have this problem/would like to have this functionality  I want to align with the previous line after the line break. Indicated in the image.

### ISSUE THREAD

**Issue by chavash17** [mpdf/mpdf#449] opened 2017-07-25 09:08 UTC
`###` I have this problem/would like to have this functionality
I want to align with the previous line after the line break. Indicated in the image.
![aca1dbce-3750-11e7-915f-8229e97958db](https://user-images.githubusercontent.com/30432353/28564333-53ec01a0-7146-11e7-94d6-e51a79249527.jpg)
Can I align this in any way?

### These are mPDF and PHP versions I am using
mPDF 6.1.0 released
PHP 5.6.30
### This is a HTML code snippet I use
```
<table cellspacing="0" cellpadding="2" class="dataChart">
<thead>
  <tr class="caption">
    <th>Norma</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="mce-content-body"><ol>
      <li><strong>Na preparação da atividade</strong>:
        <ol>
        <li>Só será liberado o trabalho em manutenção após a emissão da&nbsp;<strong>OS.</strong></li>
        <li>Antes de iniciar a tarefa, certifique-se que esteja utilizando todos os <strong>EPI's</strong>.</li>
        <li>Somente será realizada por <strong>trabalhadores Habilitados, Qualificados, Capacitados e autorizados </strong>para função.</li>
        <li>Verificar as condições <strong>do local</strong>, se existe algum<strong> risco</strong> adicional a atividade a ser executada.</li>
 ........

```

```
```

**Comment by finwe** [comment] 2017-07-25 11:41
Duplicate of #397

**Closed by finwe** 2017-07-25 11:41 UTC
