### ISSUE TITLE
Make PDF with https access

### ISSUE THREAD

**Issue by germanigortcev** [mpdf/mpdf#135] opened 2016-05-23 06:25 UTC
Excellent and very fast the formation via the http request.

When you query through https document is generated for a very long time. 1 simple page from 1 to 10 minutes.

**Comment by AndryBray** [comment] 2016-05-23 06:28
I think you have some problem with your web server. There is no difference between http & https about the mpdf process (just tested on my apache with ssl and it works as expected)

**Comment by germanigortcev** [comment] 2016-05-23 07:38
Can you display yours vhost configuration please?

**Comment by stamster** [comment] 2016-05-23 14:32
Overhead of using https should not be noticeable. It is very likely that you have some issue with your SSL endpoint configuration (web server).

**Comment by germanigortcev** [comment] 2016-05-23 14:43
I have default Apache Configuration with activated mod_ssl only and set key, ca, ca-bunlde. I don't understand what happen.

**Comment by finwe** [comment] 2016-05-23 15:12
Try setting $mpdf->showStat = true; before calling $mpdf->Output('S'). The program will then show you how much time it spent generating the PDF.

I guess you will then see that the problem is more likely in your server configuration as hinted above.

**Comment by nitinsbuzz** [comment] 2016-05-23 15:29
Check out your bindings/ vhosts settings. There could be redirection problem.

**Comment by finwe** [comment] 2016-05-23 16:58
Anyway, closing this as it appears to be unrelated to Mpdf. Feel free to reopen if you try the $mpdf->showstats variable and it shows significantly different values for http/s.

**Closed by finwe** 2016-05-23 16:58 UTC

**Comment by kisero** [comment] 2017-04-25 18:00
excellent stuff guys - thank you.

we noticed that the http request you library sent can not deal with TLS connections where the certificate is not valid (like a self-signed certificate). Have you noticed this?

**Comment by finwe** [comment] 2017-04-25 18:04
Sure, that is and should be expected behaviour. 

As many internal HTTP requests are done via simple file_get_contents call, I don't see a way this could be overriden without modifying mPDF code.

**Comment by kisero** [comment] 2017-06-26 12:57
My suggestions was to modify the code so it supports not checking for SSL certificates, wget, curl, etc have such options.

**Comment by jhowley1989** [comment] 2017-06-26 14:49
This is more of an issue with your server or PHP config.  However you could try something like:
```php
stream_context_set_default(
    array(
        'ssl' => array(
            'verify_peer' => false,
            'verify_peer_name' => false,
            'allow_self_signed' => true,
        )
    )
);
```

_untested_ but in theory it would work, [although...](https://bugs.php.net/bug.php?id=69319)

**Comment by finwe** [comment] 2017-06-26 14:51
Disabling SSL certificate validity verification is never a reasonable option. 

Better way would be adding untrusted certificate to the file set in `curl.cainfo` key in php.ini so that all functions would trust the certificate.

**Comment by jhowley1989** [comment] 2017-06-26 14:57
Probably should have prefaced my previous comment by saying this should not be used in production but could be helpful whilst developing...
