### ISSUE TITLE
PHP Parse Error (mpdf 7.0.4)

### ISSUE THREAD

**Issue by yaroslavolekh** [mpdf/mpdf#625] opened 2018-01-30 18:45 UTC
### I found this bug 
PHP Parse Error – yii\base\ErrorException
parse error, expecting `','' or `';''
in /vendor/mpdf/mpdf/src/Mpdf.php at line 60
const SCALE = 72 / 25.4;

### This is mPDF and PHP version and environment (fpm/cli etc) I am using
mpdf 7.0.4
php 5.6

**Comment by Klap-in** [comment] 2018-01-30 22:36
How is Mpdf instantiated in your setup?
Which html is feeded into mPDF, such that it triggers this error?  (please provide a _small_ html example)

This is useful for reproducing your case, and allows to create the unit test for this issue. Thanks!

**Comment by Klap-in** [comment] 2018-01-30 22:38
Hmm, reading a bit further: is that 72/25.4 supported in php5.6  for a const? I thought so..

**Comment by eafiontzi** [comment] 2018-01-31 07:51
Hello,
I am having the same bug in my production server, in development server it works like a charm but in production I get 
PHP Parse Error 'yii\base\ErrorException' with message 'syntax error, unexpected '/', expecting ',' or ';''
in /vendor/mpdf/mpdf/src/Mpdf.php:60
My php version is 7.1.3, is there any way to bypass the issue? Maybe change the constant in Mpdf.php file?
Thanks a lot

**Comment by finwe** [comment] 2018-01-31 08:19
Constant expressions are supported since PHP 5.6.0. Are you really sure you are running the code on at least this version? The code passes CI on all minor versions between 5.6.0 and 7.2.0.

**Comment by eafiontzi** [comment] 2018-01-31 08:27
![image](https://user-images.githubusercontent.com/14819444/35612345-2e249dae-0671-11e8-8828-9f63b12138ba.png)
This is what I see from my phpinfo(), could fpm be causing the problem?

**Comment by finwe** [comment] 2018-01-31 08:31
I don't think so. Is this the same PHP that is used for mPDF? There can be a different version for different hosts, for webserver and cli and so on. Are you calling `phpinfo()` on top of your mPDF script directly?

**Comment by eafiontzi** [comment] 2018-01-31 08:39
You are indeed correct when I echo phpversion() inside my script I see "Current PHP version: 5.4.45", but when I echo phpinfo inside another file I get the image above, my host is running on 7.1.13 but could it be the way I am calling my script from ./yii command directrly?

Thanks a lot

**Comment by finwe** [comment] 2018-01-31 08:42
That's what I expected, cli has a different default PHP version. There should be a `php7` or similar command available in the console, so call your yii command as `php7 yii` to get rid of the parse error.

Closing the issue as unrelated to mPDF.

**Comment by eafiontzi** [comment] 2018-01-31 08:48
Thanks a lot, it worked

**Comment by yaroslavolekh** [comment] 2018-01-31 11:16
I apologize for missing the chating. 
PHP 5.6.30 (cli) (built: Mar 11 2017 09:56:18) - it's my built. 
How to fix without upgrading php?

**Comment by finwe** [comment] 2018-01-31 11:19
@yaroslavolekh Is that really the version used while generating the PDF? if you call

    phpversion();die;

right before `new Mpdf\Mpdf();`, what is the output?

**Comment by yaroslavolekh** [comment] 2018-01-31 11:23
5.5.38 ((( i'v got it

**Comment by bluesmann** [comment] 2018-04-12 08:35
Hello,

I have the same error message. I am using 

mpdf 7.0.3.
PHP 5.3.27

How can I fix it without upgrading PHP?

**Comment by finwe** [comment] 2018-04-12 08:36
Use mPDF version 6.x

**Comment by bluesmann** [comment] 2018-04-12 08:40
the only way?

**Comment by finwe** [comment] 2018-04-12 08:41
yes.

**Comment by bluesmann** [comment] 2018-04-12 08:43
thanks a lot

**Comment by navenoc13** [comment] 2021-07-08 07:54
Hey, I'm facing the same problem.

`Unable to set PDF file protection, CSPRNG Functions are not available. Use paragonie/random_compat polyfill or upgrade to PHP 7.`

my php version is 5.6.40. 
Is there any way to fix this without upgrading php version? 

Thanks!

**Comment by finwe** [comment] 2021-07-08 07:58
What part of `Use paragonie/random_compat polyfill` do you not understand?

    composer req paragonie/random_compat

**Closed** 2021-07-08 07:59 UTC
Labels: wontfix/worksforme
