### ISSUE TITLE
OverWrite() not working

### ISSUE THREAD

**Issue by OctaneInteractive** [mpdf/mpdf#739] opened 2018-04-30 14:28 UTC
As of about an hour ago, I used Composer to install version 7.0 of MPDF in an existing and working Laravel 5.6 project.

Having followed the instructions in the [documentation](https://mpdf.github.io/reference/mpdf-functions/overwrite.html), using the code sample provided, I encountered the following error:

>App\Http\Controllers\Api\ExportController::textSearchReplace(): Failed opening required '/path/project/application/app/Http/Controllers/Api/vendor/autoload.php' (include_path='.:/Applications/MAMP/bin/php/php7.1.12/lib/php')

... because of the line: `require_once __DIR__ . '/vendor/autoload.php';` which I commented out, and then encountered another error:

> Type error: Argument 1 passed to Mpdf\Mpdf::__construct() must be of the type array, string given, called in path/project/application/app/Http/Controllers/Api/ExportController.php on line 26

Here, the error is because of the use of: `$mpdf = new \Mpdf\Mpdf('');`

However, when I replace it with: `$mpdf = new \Mpdf\Mpdf([]);` I get the following error:

> [2018-04-30 14:03:29] local.ERROR: Undefined offset: 1 {"exception":"[object] (ErrorException(code: 0): Undefined offset: 1 at /path/project/application/vendor/mpdf/mpdf/src/Mpdf.php:29307)

So I then used the code:

```
$mpdf = new \Mpdf\Mpdf([
    'tempDir' => __DIR__ . storage_path() . '/pdf/'
]);
```
... where I had set the permissions to the "pdf" folder to 777, but that triggered another error:

> Temporary files directory "/path/project/application/app/Http/Controllers/Api/path/project/application/storage/pdf/" is not writable

Something worth mentioning here is the fact that "path/project" is a long path, and it is repeated in the error. Regardless of what I do, or what path I use, the error duplicates the path. I've tried adding a spurious path and folder name and I get the same error, which suggest there is no path validation.

Here is the most recent iteration of the code:

```
$mpdf = new \Mpdf\Mpdf([
    'tempDir' => __DIR__ . storage_path() . '/pdf/'
]);

$mpdf->SetImportUse();

$mpdf->simpleTables = true;
$mpdf->packTableData = true;
$mpdf->percentSubset = 0;

$search = array(
    'DATE',
    'NAME'
);

$replacement = array(
    '11th',
    "Edit"
);

$mpdf->OverWrite(public_path() . '/pdf/experiment-simple.pdf', $search, $replacement, 'D', 'edit.pdf' );
```
Also, here's [the file I'm using](https://github.com/mpdf/mpdf/files/1960897/experiment-simple.pdf).

**Comment by finwe** [comment] 2018-04-30 14:46
Duplicate of #626

**Closed by finwe** 2018-04-30 14:46 UTC

**Comment by finwe** [comment] 2018-04-30 14:49
> ... because of the line: require_once __DIR__ . '/vendor/autoload.php'; which I commented out, and then encountered another error:

You should load the autoload file from where it actually exists, it makes sense it is not on the level where your Controllers are.

    'tempDir' => __DIR__ . storage_path() . '/pdf/'

storage_path() already contains absolute path, IIRC, therefore it is redundant and/or does not make sense along with __DIR__

> Here, the error is because of the use of: $mpdf = new \Mpdf\Mpdf('');

Was that an error on your part or is the empty string forgotten somewhere in the documentation?

The rest in #626

**Comment by OctaneInteractive** [comment] 2018-05-02 08:29
Having fixed the path to the "autoload.php" file, using the following code:

```
require_once base_path() . '/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf([
    'tempDir' => storage_path() . '/pdf/'
]);
```

I get a 500 error, with the message:

>local.ERROR: Undefined offset: 1 {"exception":"[object] (ErrorException(code: 0): Undefined offset: 1 at /path/project/application/vendor/mpdf/mpdf/src/Mpdf.php:29307)

**Comment by OctaneInteractive** [comment] 2018-05-03 10:17
Any thoughts on this? Whatever's happening has nothing to do with issue #626, as I'm not getting past the instantiation of the class.

**Comment by finwe** [comment] 2018-05-03 11:00
I seriously doubt you are getting a notice from just the class instantiation. Would you mind creating a simple unit test reproducing the error? See tests/Issues directory for examples.

**Comment by OctaneInteractive** [comment] 2018-05-03 15:08
Anything after:

```
$mpdf = new \Mpdf\Mpdf([
    'tempDir' => storage_path() . '/pdf/'
]);
```
... does not execute.

I get a 500 error, with the message:

> local.ERROR: Undefined offset: 1 {"exception":"[object] (ErrorException(code: 0): Undefined offset: 1 at /path/project/application/vendor/mpdf/mpdf/src/Mpdf.php:29307)...

There's more to the error, but it's specific to Laravel, which I could share if required.

**Comment by finwe** [comment] 2018-05-03 15:11
Copying the same message again is really not helpful. Also:

- Share your exact mPDF version
- Share the stacktrace of the error
- Share the actual expanded mPDF constructor parameters.

**Comment by OctaneInteractive** [comment] 2018-05-03 15:26
As I explained at the beginning, I'm using version 7.0.

[Error in Laravel running mPDF.txt](https://github.com/mpdf/mpdf/files/1971550/Error.in.Laravel.running.mPDF.txt)

>Share the actual expanded mPDF constructor parameters.

Other than the code sample, I don't know what else provide.

**Comment by finwe** [comment] 2018-05-03 15:29
- 7.0 is hardly specific enough.
- Your stacktrace clearly shows the error is caused by calling the OverWrite method
- #626
- Ending this discussion as it is pointless
