### ISSUE TITLE
Creates blank page after TOC 

### ISSUE THREAD

**Issue by fzanfolim** [mpdf/mpdf#1422] opened 2021-04-28 18:37 UTC
### 
when using tocpagebreak it is automatically including a blank page. I've tried using $ mpdf-> DeletePages (page); however unsuccessful, any tips?

updated to the latest version of mpdf but still have the problem

### code snippet

```
    <div class="pagina-conteudo">


    <tocpagebreak links="1" name="indice1" resetpagenum="4" margin-left="3cm" margin-top="3cm" margin-right="2cm" margin-bottom="2cm" toc-preHTML="


        &lt;h4 style=&#x22;text-align:center;&#x22;&gt; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ÍNDICE&lt;/h4&gt;
    ">


    </div>

<?

$html = ob_get_contents();
ob_end_clean();
$mpdf->WriteHTML($html);
$countIndice=0;
ob_start();
?>

```

### CSS

```
@page pagina-conteudo{header: html_myheader; footer: html_myfooter; }
@page pagina-conteudo :right{header: html_myheaderOdd; footer: html_myfooterOdd; }

.pagina-conteudo{page: pagina-conteudo; padding-left:40px; padding-right:40px; margin-left: 1.5cm !important; margin-right: 1cm !important;}
```

**Comment by finwe** [comment] 2021-04-28 19:15
Duplicate of https://github.com/mpdf/mpdf/issues/798

**Closed by finwe** 2021-04-28 19:15 UTC
