### ISSUE TITLE
bootstrap not working

### ISSUE THREAD

**Issue by ajithfort** [mpdf/mpdf#66] opened 2015-11-14 07:47 UTC
hi,

i am using mpdf in yii2. This is my controller code

    public function actionPrint_death_certificate1()
        {
    
            $this->layout   =   'certificate';
    
    
            $html   =   $this->render('test');
            require_once(Yii::$app->basePath . "/../vendor/mpdf/mpdf/mpdf.php");
            $mpdf=new mPDF();
            $mpdf->WriteHTML($html);
            $mpdf->Output();
    
        }

my view

    <div class="container">
    	<div class="row">
    		<div class="col-md-6">
    		Heading1
    		</div>
    		<div class="col-md-6">
    		Heading2
    		</div>
    	</div>
    </div>

now i get a pdf with heading1 and heading2 in two different lines. Bootstrap is not working. Am i missing something?

    return $this->render('test');

when i tried this one it is working and heading1 and heading2 is coming in one line. In pdf it is not working

**Comment by finwe** [comment] 2015-11-16 13:31
Are you sure that Yii includes layout on `$this->render('test');` call and not some time after return from action method? 

Does

```
var_dump($this->render('test'));
die();
```

produce an entire HTML including layout or only the view portion?

**Comment by ajithfort** [comment] 2015-11-18 04:33
hi,

1) my layout is certificate.php which is as follows
```<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <link rel="stylesheet" href="<?php echo Yii::$app->getUrlManager()->getBaseUrl();?>/css/certificate.css" type='text/css' media='all' />
	<link rel='stylesheet' id='zn-bootstrap-responsivecss-css' href="<?php echo Yii::$app->getUrlManager()->getBaseUrl();?>/css/certificate-responsive.css" type='text/css' media='all' />
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<?php $this->head() ?>
    
</head>
<body class="page page-id-2216 page-template-default res1170">
    <?php $this->beginBody() ?>
		<?php echo $content; ?>
	    <?php $this->endBody() ?>
</body>
</html>

<?php $this->endPage() ?>```

and i am quite sure that  Yii includes layout on $this->render('test'); call.

2) var_dump($this->render('test'));
die(); this gave me an output like this

```string(1199) "
Heading1 Heading2 "```

**Comment by finwe** [comment] 2015-11-18 12:23
Judging by some simple try/error testing, there are problems with bootstrap coming from pseudo device-width of the document, print media styles and page margins. 

`col-md-6` class has full page width when used in mPDF document, as `col-sm-6` has. The only class getting somewhat correctly resized to 50% is `col-xs-6`, but the width is computed from whole page width, not excluding page margins, so the columns are also stacked instead of displayed alongside each other.

![mpdf-bootstrap](https://cloud.githubusercontent.com/assets/195675/11241002/64bf6c08-8df7-11e5-867d-4c0aee297c6d.png)

I will close this issue now with resolution "bootstrap not supported out-of-the-box". You could use some custom style to make the columns fit when exporting to PDF.

Given some enthusiasm, maybe the community will be able to look into this sometime in the future.

**Closed by finwe** 2015-11-18 12:23 UTC

**Comment by Lizethe** [comment] 2015-11-20 12:53
Bootstrap is external to the default styles for mpdf, which is why classes bootstrap your pdf not work, as I said before if you want to customize the look of your pdf need to use a piece of own style and add after creating your MPDF. In short bootstrap not work to generate PDF with MPDF.

**Comment by Lizethe** [comment] 2015-11-20 12:59
Bootstrap is external to the default styles for fpdf, which is why classes bootstrap your pdf not work, if you want to customize the look of your pdf need to use a piece of own stylesheets, add after creating your mpdf and use your classes stylesheets. In short bootstrap not work to generate PDF with mpdf.

public function actionPrint_death_certificate1()
{
    $this->layout = 'certificate';
    $html = $this->render('test');
    $stylesheet = file_get_contents('style.css');
    require_once(Yii::$app->basePath . "/../vendor/mpdf/mpdf/mpdf.php");
    $mpdf = new mPDF();
    $mpdf->WriteHTML($stylesheet, 1);
    $mpdf->WriteHTML($html);
    $mpdf->Output();
}

**Comment by fredrabelo** [comment] 2016-10-26 05:23
Any update on this issue? Bootstrap grid still not supported on mpdf? 

I am having the same problem and I really don't want to create a different template just for printing with mpdf, no way to replace all the col-xs-* bootstrap grid with tables.

**Comment by developerpratika** [comment] 2016-11-30 12:59
Any update on this issue? Bootstrap grid still not supported on mpdf?

**Comment by finwe** [comment] 2016-11-30 13:02
No, bootstrap grid is still not supported and nobody is working on the support.

**Comment by Blair2004** [comment] 2016-12-04 08:08
Same issue, no clear solutions... maybe with custom stylesheet

**Comment by anguswild** [comment] 2017-06-30 19:08
I think i found a workaround

First we Override the bootstrap css (i use a 10px top-margin for the row but this is not necessary) :

```
.row {
margin: 10px 0px 0px 0px !important;
padding: 0px !important;
}
```
a then we set the columns like this

```
<div class="row">
    <div class="col-xs-6 col-sm-6">TEST</div>
    <div class="col-sm-6">RUT: </b>TEST</div>
</div> 
<div class="row">
    <div class="col-xs-4 col-sm-4">TEST</div>
    <div class="col-xs-4 col-sm-4">TEST</div>
    <div class="col-sm-4">TEST</div>
</div> 

```

**Comment by synnoc** [comment] 2017-10-09 15:49
This works for me
```
.col-xs-1, .col-sm-1, .col-md-1, .col-lg-1, .col-xs-2, .col-sm-2, .col-md-2, .col-lg-2, .col-xs-3, .col-sm-3, .col-md-3, .col-lg-3, .col-xs-4, .col-sm-4, .col-md-4, .col-lg-4, .col-xs-5, .col-sm-5, .col-md-5, .col-lg-5, .col-xs-6, .col-sm-6, .col-md-6, .col-lg-6, .col-xs-7, .col-sm-7, .col-md-7, .col-lg-7, .col-xs-8, .col-sm-8, .col-md-8, .col-lg-8, .col-xs-9, .col-sm-9, .col-md-9, .col-lg-9, .col-xs-10, .col-sm-10, .col-md-10, .col-lg-10, .col-xs-11, .col-sm-11, .col-md-11, .col-lg-11, .col-xs-12, .col-sm-12, .col-md-12, .col-lg-12 {
	border:0;
	padding:0;
	margin:0;
}
```

**Comment by talamihg** [comment] 2017-10-23 20:59
For the most part that helped, not all of my Bootstrap styled HTML is being displayed in the Bootstrap styled grid.

**Comment by Klap-in** [comment] 2017-10-23 21:06
Reading this, it looks like that an alternative css style for export as pdf is the way to improve the situation. If you can come up with some general recommendations for Bootstrap, I think it is worth a help page at https://mpdf.github.io/

**Comment by luciash** [comment] 2018-02-12 10:55
@synnoc IMHO `margin-left:-0.00001;` is useless with no unit specified.

**Comment by SzymonDukla** [comment] 2018-10-18 10:04
Still no fix to that?

**Comment by Rohit-Infobeans** [comment] 2018-10-29 10:17
How we can use bootstrap in mpdf?

**Comment by wimurk** [comment] 2018-12-18 12:58
> This works for me
> 
> ```
> .col-xs-1, .col-sm-1, .col-md-1, .col-lg-1, .col-xs-2, .col-sm-2, .col-md-2, .col-lg-2, .col-xs-3, .col-sm-3, .col-md-3, .col-lg-3, .col-xs-4, .col-sm-4, .col-md-4, .col-lg-4, .col-xs-5, .col-sm-5, .col-md-5, .col-lg-5, .col-xs-6, .col-sm-6, .col-md-6, .col-lg-6, .col-xs-7, .col-sm-7, .col-md-7, .col-lg-7, .col-xs-8, .col-sm-8, .col-md-8, .col-lg-8, .col-xs-9, .col-sm-9, .col-md-9, .col-lg-9, .col-xs-10, .col-sm-10, .col-md-10, .col-lg-10, .col-xs-11, .col-sm-11, .col-md-11, .col-lg-11, .col-xs-12, .col-sm-12, .col-md-12, .col-lg-12 {
> 	border:0;
> 	padding:0;
> 	margin-left:-0.00001;
> }
> ```

This actually worked

**Comment by Ivcho-Varna** [comment] 2020-02-03 17:30
I figured out that the issue is caused by the printing styles of bootstrap. Specifically the following line:

`    @page {
      size: $print-page-size;
    }
`

When i add this to my stylesheet the PDF renders fine.

`
            @media print {
                @page {
                    size: auto;
                }
            }
`

Hope it helps somebody.

Cheers :)

**Comment by navintanzim** [comment] 2022-09-13 04:29
Fast Forward 2022, and the problem is now even worse. Tried everything mentioned here on a stylesheet of Bootstrap v3.3.4 and none of them worked. I think I am gonna have to switch to another service to make my pdfs.

**Comment by pfpro** [comment] 2023-05-16 21:44
which one would that be - dompdf?

**Comment by finwe** [comment] 2023-05-17 04:57
@pfpro It is right in the readme https://github.com/mpdf/mpdf#about-css-support-and-development-state
