### ISSUE TITLE
"total number of pages"-placeholder {ng} is not working if not set in Header or Footer

### ISSUE THREAD

**Issue by kenowessels** [mpdf/mpdf#535] opened 2017-11-10 09:53 UTC
### I found this bug / would like to have this new functionality
The `total number of pages` placeholder {ng} seems to work only in the Header and Footer.
The example given [here](https://mpdf.github.io/reference/mpdf-functions/aliasnbpages.html#examples) does not work.

### This is mPDF and PHP version and environment (fpm/cli etc) I am using
- PHP 7.0.22
- Mpdf 7.0.1 (bug seems to exist since 6.X,  see https://github.com/mpdf/mpdf/issues/267)
### This is a PHP code snippet I use

```
<?php
        $mpdf = new \Mpdf\Mpdf();

        $mpdf->AliasNbPages('[pagetotal]');
        $mpdf->WriteHTML('
There are [pagetotal] pages in this document
');

        $mpdf->Output();
```

**Comment by finwe** [comment] 2017-11-10 10:21
Thanks for the report, marking as duplicate of #267 and will look into it eventually. maybe.

**Closed by finwe** 2017-11-10 10:21 UTC
