### ISSUE TITLE
PHP Notice – yii\base\ErrorException Undefined index: list_style_image

### ISSUE THREAD

**Issue by attybean** [mpdf/mpdf#886] opened 2018-10-17 08:36 UTC
https://github.com/mpdf/mpdf/blob/fb339f4ef1e584d72b820a06e7139a72eb2851b7/src/Tag/BlockTag.php#L898

Suggested solution:
Replace line 898:
`$this->mpdf->_setListMarker($currblk['list_style_type'], $currblk['list_style_image'], $currblk['list_style_position']);`

With the following:
`$this->mpdf->_setListMarker($currblk['list_style_type'], $currblk['list_style_image']??'none', $currblk['list_style_position']??'outside');`

**Comment by Klap-in** [comment] 2018-10-17 08:51
Could you provide the following details as well. 
Especially an example of your initialization of mpdf instance is needed and minimal example of your html. These are used to create an unit test to prove your case is really solved. Thank you very much!


    ### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
    
    ### This is a PHP code snippet I use
    
    ```
    <?php
    
    
    ```
    
    ### This is a HTML/CSS code snippet I use
    
    ```
    
    ```

**Comment by finwe** [comment] 2018-10-17 09:48
Duplicate of https://github.com/mpdf/mpdf/issues/853

**Closed by finwe** 2018-10-17 09:48 UTC
Labels: missing sample / test, notices-warnings
