### ISSUE TITLE
<a> tag is showing weird div on hover - see attached

### ISSUE THREAD

**Issue by edionmelarosa** [mpdf/mpdf#378] opened 2017-04-20 02:02 UTC
### <a> tag is showing weird div on hover. 
<img width="464" alt="cb7e456f1e3bf52a03867640934ea8aa" src="https://cloud.githubusercontent.com/assets/8658101/25209962/654034a8-25b0-11e7-8f96-610b68f13dfc.png">

### This is a PHP code snippet I use

```
<?php


 $html = '';
        $url = "pdf page url";
        $url = urldecode($url);

        if (count($_POST) > 0) {

            $ch = curl_init($url);
            curl_setopt($ch, CURLOPT_HEADER, 0);
            curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1 );

            foreach($_POST as $name => $post) {
              $formvars = array($name => $post . " \n");
            }

            curl_setopt($ch, CURLOPT_POSTFIELDS, $formvars);
            $html = curl_exec($ch);
            curl_close($ch);

        } elseif (ini_get('allow_url_fopen')) {
            $html = file_get_contents($url);

        } else {
            $ch = curl_init($url);
            curl_setopt($ch, CURLOPT_HEADER, 0);
            curl_setopt ( $ch , CURLOPT_RETURNTRANSFER , 1 );
            $html = curl_exec($ch);
            curl_close($ch);
        }

        if ($html) {
            $mpdf = new mPDF('utf-8', 'A4-L');

            //$mpdf->useSubstitutions = true; // optional - just as an example
            //$mpdf->SetHeader($url . "\n\n" . 'Page {PAGENO}');  // optional - just as an example
            $mpdf->allow_charset_conversion = TRUE;

            $mpdf->CSSselectMedia = ['screen', 'print']; // assuming you used this in the document header
            $mpdf->setBasePath($url);
            //$mpdf->SetHTMLFooter("<h2>djhfhf</h2>");
            $mpdf->WriteHTML($html, 0);

            $mpdf->Output();
        } else {
            echo 'Error generating PDF';
        }

### This is a HTML code snippet I use

```
 <a href="link" target="_blank" class="complete-order-btn">COMPLETE ORDER</a>
```

**Comment by finwe** [comment] 2017-04-20 11:08
Duplicate of #283

**Closed by finwe** 2017-04-20 11:08 UTC
