### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable in C in Joomla ...Please help me the fix this 

### ISSUE THREAD

**Issue by ureshchamara** [mpdf/mpdf#595] opened 2017-12-29 08:45 UTC
I have restored my site from backup using Akeeba kick start and after restore is completed below error msg showing on site and even in admin panel as well (in Joomla )

Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\mywebsite\libraries\cms\application\cms.php on line 470
any help would be appreciate .

thank you.

**Comment by Klap-in** [comment] 2017-12-29 08:57
I guess you have similar issue as: #562

How is Mpdf instantiated in your setup?
Which html is feeded into mPDF, such that it triggers this error?  (please provide a _small_ html example)

This is useful for reproducing your case, and allows to create the unit test for this issue. Thanks!

**Comment by ureshchamara** [comment] 2017-12-29 08:58
![image](https://user-images.githubusercontent.com/34935670/34433328-00d96e44-ec98-11e7-9e96-1ecc20775e4c.png)

**Comment by Klap-in** [comment] 2017-12-29 09:08
Yes, the error we see, but because the error could be triggered in more ways, we need answer on the following questions. Thanks for the efforts answering them!

- How is Mpdf instantiated in your setup?
- Which html is feeded into mPDF, such that it triggers this error? (please provide a small html example)

**Comment by ureshchamara** [comment] 2017-12-29 09:13
ok. here it is (php)
![image](https://user-images.githubusercontent.com/34935670/34433635-0fbc069a-ec9a-11e7-83bc-d96c55e9097c.png)

and no idea about "How is Mpdf instantiated in your setup?"

**Comment by ureshchamara** [comment] 2017-12-29 10:23
Any updates please?

**Comment by finwe** [comment] 2017-12-30 18:38
The error is in your code, not in mPDF. Closing.

**Closed by finwe** 2017-12-30 18:38 UTC

**Comment by mohipan** [comment] 2018-03-31 13:33
Hello  @ureshchamara  please type your coding like this:
public function getMessageQueue ($ clear = false)
{
// For empty queue, if messages exists in the session, enqueue them.
if (! count ($ this -> _ messageQueue))
{
$ session = JFactory :: getSession ();
$ sessionQueue = $ session-> get ('application.queue');

if (! count ($ this -> _ messageQueue))
{
$ this -> _ messageQueue = $ sessionQueue;
$ session-> set ('application.queue', null);
}
}
$ messageQueue = $ this -> _ messageQueue;

if ($ clear)
{
$ this -> _ messageQueue = array ();
}

return $ messageQueue;
}

good luck
do not forget the mapir on my site
http://mohipan.co.id/

**Comment by 0215526** [comment] 2018-04-07 05:48
public function getMessageQueue()
	{
		// For empty queue, if messages exists in the session, enqueue them.
		if (!count($this->_messageQueue))
		{
			$session = JFactory::getSession();
			$sessionQueue [] = $session->get('application.queue');

			if (count($sessionQueue))
			{
				$this->_messageQueue = $sessionQueue;
				$session->set('application.queue', null);
			}
		}

		return $this->_messageQueue;
	}
// make sessionQueue to array []

**Comment by Alejandrollg** [comment] 2018-07-01 11:07
Gracias por esta solución:
// make sessionQueue to array []
$sessionQueue [] = $session->get('application.queue');
Es una tonteria que la advertencia sea por que esta pidiendo un array para este tipo de contador y no una variable normal.
Genial solucionado mi error

**Comment by sandeepy8222** [comment] 2018-08-01 07:14
I'm new beginner in Joomla.  And Im getting these errors please help to fix these errors 

Warning: count(): Parameter must be an array or an object that implements Countable in H:\Xampp\htdocs\Antaral\components\com_k2store\helpers\cart.php

 Warning: count(): Parameter must be an array or an object that implements Countable in H:\Xampp\htdocs\Antaral\plugins\system\helix3\core\classes\menu.php on line 268

Thank you 
Sandeep

**Comment by Klap-in** [comment] 2018-08-01 08:10
Sorry: cart.php and menu.php don't exist in the mPDF software. 

If you have a real bug, please post at least small but complete php and html examples to let your helpers reproduce your case. For troubleshooting you better use https://stackoverflow.com/questions/tagged/mpdf

**Comment by rooyti** [comment] 2019-01-18 00:43
> 
> 
> 
> 
> ```
> public function getMessageQueue($clear = FALSE)
> {
> 	// For empty queue, if messages exists in the session, enqueue them.
> 	if (!count($this->_messageQueue)) {
> 		$session = JFactory:: getSession();
> 		$sessionQueue = $session->get('application.queue');
> 
> 		if (!count($this->_messageQueue)) {
> 			$this->_messageQueue = $sessionQueue;
> 			$session->set('application.queue', NULL);
> 		}
> 	}
> 	$messageQueue = $this->_messageQueue;
> 
> 	if ($clear) {
> 		$this->_messageQueue = [];
> 	}
> 
> 	return $messageQueue;
> }
> ```
> 
> good luck

> Where is the php ?
