### ISSUE TITLE
Undefined index: list_style_type at mpdf\src\Tag\BlockTag.php:898

### ISSUE THREAD

**Issue by rottndandie** [mpdf/mpdf#951] opened 2019-01-09 16:23 UTC
### I found this bug
Undefined index: list_style_type at F:\\xampp\\htdocs\\myproject\\vendor\\mpdf\\mpdf\\src\\Tag\\BlockTag.php:898)

Stack trace:

```
F:\\xampp\\htdocs\\myproject\\vendor\\mpdf\\mpdf\\src\\Tag\\BlockTag.php(898): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', 'F:\\\\xampp\\\\htdocs...', 898, Array)
#1 F:\\xampp\\htdocs\\myproject\\vendor\\mpdf\\mpdf\\src\\Tag.php(243): Mpdf\\Tag\\BlockTag->open(Array, Array, 1)
#2 F:\\xampp\\htdocs\\myproject\\vendor\\mpdf\\mpdf\\src\\Mpdf.php(13620): Mpdf\\Tag->OpenTag('LI', Array, Array, 1)
#3 F:\\xampp\\htdocs\\myproject\\app\\CustomClasses\\PDFMaker.php(525): Mpdf\\Mpdf->WriteHTML(' <li>a favorabl...')
#4 F:\\xampp\\htdocs\\myproject\\app\\Http\\Controllers\\UsersController.php(688): App\\CustomClasses\\PDFMaker::makeManual(Object(App\\User))
```

### This is the mPDF and PHP version and environment (server/fpm/cli etc) I am using
mpdf 7.1
PHP 7.0

### This is the PHP code snippet I use

            $files = scandir($masterpath);
            foreach( $files as $file ) {
                if($file == '.' || $file == '..')
                    continue;
                $filelocation = $masterpath.$file;
                $handle = fopen($filelocation, "r");
                if ($handle) {
                    while (($line = fgets($handle)) !== false) {
                        // write it to the PDF
                        $mpdf->WriteHTML($line);
                    }
                
                    fclose($handle);
  
                } else {
                    // error opening the file.
                    return back()->with('error', 'Could not locate the manual. Please contact tech support.');
                } 
            }   
            
            /* BOTTOM OF FILE */
            $mpdf->WriteHTML('</div>');

            //make the user download it right now. We're not going to store these files
            $mpdf->Output($pdffilename, \Mpdf\Output\Destination::DOWNLOAD); 
  
### This is the HTML/CSS code snippet I use

```
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent fringilla mollis mi, ut sagittis felis pretium tincidunt. Aliquam vitae auctor ipsum, nec tempor elit: 
</p>
    <ul>
    <li>
a favorable decision is based on symptom remission, and 
</li>
    <li>
the respondent is seeking escape or release from confinement. 
</li>
    </ul>
    <p>
Proin volutpat in est in dictum. Ut et est scelerisque, condimentum nibh nec, ultricies nunc. Mauris id eros vestibulum, ornare urna id, interdum augue. Sed nec consectetur leo. 
</p>
```

Everything works fine if I remove the ul and li tags and put the text in a p but the whole manual is filled with unordered and ordered lists.

**Comment by finwe** [comment] 2019-01-09 17:11
Also check your HTML, I guess you are missing a closing tag somewhere or have tags crossed.

**Comment by rottndandie** [comment] 2019-01-09 17:42
I can't figure out how to post the actual HTML code here so that it shows up as HTML code and not the formatted text. Help? Google didn't :( I'm putting spaces to try to trick this window but the actual HTML is SUPER simple. ;)

The error in the stacktrace points to the first li element ("a favorable...") so this is where I presume the exception happens. When I remove the ul and li tags and replace with p tags, it works fine.

< p >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent fringilla mollis mi, ut sagittis felis pretium tincidunt. Aliquam vitae auctor ipsum, nec tempor elit: < /p >
< ul >
    < li >a favorable decision is based on symptom remission, and < /li >
    < li >the respondent is seeking escape or release from confinement. < /li >
< /ul >
< p >Proin volutpat in est in dictum. Ut et est scelerisque, condimentum nibh nec, ultricies nunc. Mauris id eros vestibulum, ornare urna id, interdum augue. Sed nec consectetur leo. < /p >

**Comment by finwe** [comment] 2019-01-09 18:00
This is the same HTML code. It works OK. I need an entire code snippet that actually fails. Otherwise I am unable to reproduce and fix this accordingly.

Use three backticks "`" above and under your code snippet to preserve HTML. Use preview tab above the comment textarea to try it.

**Comment by rottndandie** [comment] 2019-01-09 18:22
Got ya. Here's the entire PHP method that's creating the manual. The first file in the $masterpath dir contains the HTML code I've shared above and nothing else. mPDF fails when it reaches the li tag every time, so none of the other files get processed.

        public static function makeScoringManual($user)
    {
        $tag = '[PDFMaker::makeScoringManual] ';
        $email = $user->email;
        $name = $user->name;

        $pdffilename = 'SCORING_MANUAL.pdf';
        $copyrightyear = date('Y');
        $masterpath = resource_path('views/help/manual/');

        //create the PDF object
        //For those in the US and Canada, use letter; otherwise, use the default A4
        if($user->country_code == 'US' || $user->country_code == 'CA')
            $mpdf = new \Mpdf\Mpdf(['format' => 'Letter']);
        else
            $mpdf = new \Mpdf\Mpdf(['format' => 'A4']);

        try {
            //set header, footer and watermark
            $mpdf->SetHTMLHeader('
                <div style="text-align: center; font-weight: bold;">
                    WAS Scoring Manual for '.$name.' ('.$email.') </div>');

            $footertext = '<table width="100%">';
            $footertext .= '<tr><td colspan="3" style="font-size:10px; text-align:center;">&nbsp;</td></tr>';
            $footertext .= '<tr>
                    <td width="33%"><small>{DATE Y-m-d}</small></td>
                    <td width="33%" align="center"><small>page {PAGENO}/{nbpg}</small></td>
                    <td width="33%" style="text-align: right;"><small>&copy;'.$copyrightyear.' by Rottndandie</small></td>
                </tr>
            </table>';

            $mpdf->SetHTMLFooter($footertext);
            $mpdf->SetWatermarkImage("/img/TheLogo.jpg", 0.2, 'F');
            $mpdf->watermarkImgBehind = true;
            $mpdf->showWatermarkImage = true;

            //set PDF options
            //user can open and print but not copy or modify without the secret password, which we
            //don't tell him because it's random and even we don't know what it is.
            $mpdf->SetProtection(array('annot-forms', 'print', 'print-highres'), '', MyUtils::generateRandomString(15, false));

            /* TOP OF FILE */
            $mpdf->WriteHTML('<div class="col-12">');                
                
            //foreach file in the $masterpath dir, write the contents line by line to the PDF
            $files = scandir($masterpath);
            foreach( $files as $file ) {
                if($file == '.' || $file == '..')
                    continue;
                $filelocation = $masterpath.$file;
                $handle = fopen($filelocation, "r");
                if ($handle) {
                    while (($line = fgets($handle)) !== false) {
                        // write it to the PDF
                        $mpdf->WriteHTML($line);
                    }
                
                    fclose($handle);
                    $mpdf->AddPageByArray(['mgb' => '12']); //tighten top/bottom margins                    
  
                } else {
                    // error opening the file.
                    return back()->with('error', 'Could not locate the WASSM. Please contact tech support.');
                } 
            }   

            /* BOTTOM OF FILE */
            $mpdf->WriteHTML('</div>');

            //make the user download it right now. We're not going to store these files
            $mpdf->Output($pdffilename, \Mpdf\Output\Destination::DOWNLOAD);                      
        } //end try 
        catch (\Mpdf\MpdfException $e) { 
            Log::error($tag. $e->getMessage());
        }           
    }

**Comment by finwe** [comment] 2019-01-09 20:12
No, this code with your HTML snippet still works. Please see https://stackoverflow.com/help/mcve and feel free to reopen with code that can be copypasted as a whole and fails.

**Closed by finwe** 2019-01-09 20:12 UTC
Labels: bug/fix, missing sample / test, notices-warnings
