### ISSUE TITLE
Move fonts into an own optional repository

### ISSUE THREAD

**Issue by alexander-schranz** [mpdf/mpdf#1632] opened 2022-04-02 21:17 UTC
# Feature request

The repository is shipped with about 90mb folder of fonts. It would be nice to make that fonts optional.

The font directory seems already be configureable so already an own directry can be used: https://github.com/mpdf/mpdf/blob/3b21745a7b0178c14bf512d79b790a4351c16bce/src/Config/ConfigVariables.php#L450-L452

So only splitting into a separate package example `mpdf/fonts` would be needed. Add the following class to that package then:

```php
namespace Mpdf\Font;

class FontLocator {
   public static function locate() {
       return dirname(__DIR__) . '/ttfonts';
   }
}
```

so you can use as default in the config:

```php
'fontDir' => array_filter([
    class_exists('\Mpdf\Font\FontLocator') ? \Mpdf\Font\FontLocator::locate() : null,
]),
```

If fonts are always require you could throw following exception:

```php
throw new \RuntimeException('Install "mpdf/fonts" package or configure a custom "fontDir".');
```

For backward compatibility reasons `"mpdf/fonts"` can be first added as `require` of this package and in the next major release set to `require-dev`. With having it as own package also when it is set as `require` I can avoid that `mpdf/fonts` is installed by adding `"replace": {"mpdf/fonts": "*"}` to my project `composer.json`, this technic is used example to avoid install of polyfills of php versions when you already using that php version ([example](https://github.com/sulu/skeleton/blob/8331c01ac4b45a3d2b1dd2074f5484ad29803091/composer.json#L76-L79)).

**Comment by finwe** [comment] 2022-04-02 21:20
Duplicate of #552, #841

**Closed by finwe** 2022-04-02 21:20 UTC

**Comment by alexander-schranz** [comment] 2022-04-03 12:34
Looks like there is not a lot of progress on #841. what do you think by only putting the fonts into a seperate package? So no changes about the font metrics data and so on, think that something I could contribute if that would be a solution for you.

**Comment by finwe** [comment] 2022-04-03 17:05
That seems as a half-assed solution I am not particularly fond of.
