### ISSUE TITLE
CSS text-align: center does not work properly when on p inside table>tr>td

### ISSUE THREAD

**Issue by segaltre** [mpdf/mpdf#200] opened 2016-07-26 07:17 UTC
Hi
### This is a HTML code snippet I use

```
<table style="width: 99%;">
  <tr>
    <td><p class="text-center">-</p></td>
    <td><p style="text-align: center;">-</p></td>
  </tr>
  <tr>
    <td class="text-center"><p>+</p></td>
    <td style="text-align: center;"><p>+</p></td>
  </tr>
</table>
```

Regards

**Comment by finwe** [comment] 2016-07-26 09:47
Define "not working"

**Comment by segaltre** [comment] 2016-07-26 11:21
Alignment (text-align: center).

**Comment by jakejackson1** [comment] 2016-07-26 23:36
Not a bug. Block-level elements are ignored inside tables. Please refer to the manual for more details: http://mpdf.github.io/tables/tables.html

**Comment by segaltre** [comment] 2016-07-27 04:36
Really? It doesn't work as expected.

HTML: [jsfiddle](https://jsfiddle.net/960xm5xr/)
PDF (screen):
![screen](https://cloud.githubusercontent.com/assets/8143230/17163884/b880284a-53dc-11e6-9b65-f890a7e358fb.png)

If it not a bug, so why this plugin use HTML?

**Comment by finwe** [comment] 2016-07-27 07:17
Thanks, Jake, i guessed it will be noted somewhere in the documentation, it just didn't occur to me it will be on tables page.

It's not a bug as it is documented (and thus for mPDF expected) behaviour. It just isn't supported ATM. 

Will leave this open as an enhancement for the future.

**Comment by smileysharma** [comment] 2018-12-21 09:47
Hello Finwe, 

can you tell me when we can expect this enhancement ? as that is main requirement in my task to center a part of text inside table data. A suggestion: I think if you can allow display properties to be change then it can also work because as per documentation td is using display proerty as table however it should be table cell to make inside block properties to work. 

Thanks.

**Comment by finwe** [comment] 2018-12-21 09:48
It is marked as help wanted. Unless someone puts wotrk to this, do not expect this any time (soon).

**Comment by smileysharma** [comment] 2018-12-21 09:58
we you tell me any quick fix or something  so that I can still keep using it with any hotfix?

**Comment by smileysharma** [comment] 2018-12-21 10:22
can't you give us option to control display property in pdf ?

**Comment by finwe** [comment] 2018-12-21 12:48
no, sorry.

**Comment by finwe** [comment] 2022-04-05 20:08
Closing as stale, it will probably not happen, see the development notice in the readme.

**Closed by finwe** 2022-04-05 20:08 UTC
Labels: feature/enhancement, help wanted
