### ISSUE TITLE
 Who was an error this was not ạ :(

### ISSUE THREAD

**Issue by TrungPhuNA** [mpdf/mpdf#788] opened 2018-06-26 09:27 UTC
if (isset($properties['VERTICAL-ALIGN'])) {
            $objattr['vertical-align'] = self::ALIGN[strtolower($properties['VERTICAL-ALIGN'])];
        }
 
        $colsize = 20; //HTML default value
        $rowsize = 2; //HTML default value
        if (isset($attr['COLS'])) {
            $colsize = (int) $attr['COLS'];
        }
        if (isset($attr['ROWS'])) {
            $rowsize = (int) $attr['ROWS'];
        }
 
        $charsize = $this->mpdf->GetCharWidth('w', false);
 
        if ($w) {
 
            // default
            $colsize = round(($w - ($this->form->form_element_spacing['textarea']['outer']['h'] * 2)
                    - ($this->form->form_element_spacing['textarea']['inner']['h'] * 2)) / $charsize);
 
        }
        if ($h) {
            $rowsize = round(($h - ($this->form->form_element_spacing['textarea']['outer']['v'] * 2)
                    - ($this->form->form_element_spacing['textarea']['inner']['v'] * 2)) / $this->mpdf->lineheight);
        }
 
        $objattr['type'] = 'textarea';
        $objattr['width'] = ($colsize * $charsize) + ($this->form->form_element_spacing['textarea']['outer']['h'] * 2)
            + ($this->form->form_element_spacing['textarea']['inner']['h'] * 2);
 
        $objattr['height'] = ($rowsize * $this->mpdf->lineheight)
            + ($this->form->form_element_spacing['textarea']['outer']['v'] * 2)
            + ($this->form->form_element_spacing['textarea']['inner']['v'] * 2);
 
        $objattr['rows'] = $rowsize;
        $objattr['cols'] = $colsize;
 
        $this->mpdf->specialcontent = serialize($objattr);
 
Arguments
"Division by zero"

**Comment by TrungPhuNA** [comment] 2018-06-26 09:28
Help my :(

**Comment by Klap-in** [comment] 2018-06-26 10:17
Please note that this is not a reproducible example of your case. Please update.

**Comment by TrungPhuNA** [comment] 2018-06-26 10:19
is that Can you explain it yourself? thank you @Klap-in

**Comment by TrungPhuNA** [comment] 2018-06-26 10:20
@Klap-in . This is a bug that is fired

**Comment by Klap-in** [comment] 2018-06-26 10:20
Your example is not complete. It misses information.

**Comment by TrungPhuNA** [comment] 2018-06-26 10:21
@Klap-in   : I do not understand
 :( Help my

**Comment by Klap-in** [comment] 2018-06-26 10:21
I cannot test it on my machine, because you left out information.

This is what we need: https://github.com/mpdf/mpdf/tree/development/tests/Issues

**Comment by TrungPhuNA** [comment] 2018-06-26 10:27
https://github.com/mpdf/mpdf/compare/development...TrungPhuNA:patch-1#diff-1f2f88381a26a7b38492f26bbd3d0ad8

**Comment by TrungPhuNA** [comment] 2018-06-26 10:33
https://github.com/mpdf/mpdf/pull/790/commits/5f0d9383af42509c2682679ccd2e2d7be95eeb09

**Comment by TrungPhuNA** [comment] 2018-06-26 10:34
I just pushed code to github

**Comment by finwe** [comment] 2018-06-26 10:59
Not helpful. That issue template is not there for nothing, you know. 

What is your mPDF version? How do you initialize the Mpdf object?

And unless you share an entire pure-HTML snippet, we cannot reproduce your issue.

Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to easier reproduce the issue.

**Closed by finwe** 2018-06-26 10:59 UTC
