### ISSUE TITLE
italic style issue in Arabic language 

### ISSUE THREAD

**Issue by faroukmhammad** [mpdf/mpdf#689] opened 2018-03-18 15:02 UTC
Version:  5.7.1  or 6
when try use html tag (<em> ,<i>) it's work fine with English language but when convert html to pdf(arabic lange) example : التامين الصحي  text display as  square  
look to image : 
![joxi_screenshot_1521385263404](https://user-images.githubusercontent.com/15747592/37567327-210cdaf6-2ace-11e8-9388-70276db81d11.png)

**Comment by finwe** [comment] 2018-03-18 20:49
Duplicate of #690

**Closed by finwe** 2018-03-18 20:49 UTC
